### ISSUE TITLE
Meteor or Volt like in Python

### ISSUE THREAD

**Issue by miguelalarcos** [kovidgoyal/rapydscript-ng#1]
Hi, first of all let me say you that your work is awesome.

I was thinking, just thinking, in something like `Meteor` or `Ruby Volt` in `Python`. Do you know them? It has to be with reactive programming.

I think `rapydscript-ng` is perfect for that but there's the need of a template language to compile to javascript that manage de `DOM` (and subscribe to reactive source data to redisplay the data when it changes). Do you know if `rapydML` is a good starting point for that?

I hope I've explained correctly the problem. In other case please let me know. Thanks :)

**Comment by kovidgoyal** [comment]
Personally, I am not a user of templating languages to manage/create the DOM. I find that managing it just with pure rapydscript is fine on modern browsers :) You'd have to to ask @atsepkov about rapydml, he is it's creator -- it is not something I use or know anything about, sorry.

**Comment by amitu** [comment]
@miguelalarcos I have been experimenting with using react with rs-ng, you can check a TodoMVC example here: https://github.com/amitu/vyom/tree/master/TodoMVC.
