### ISSUE TITLE
Errors with equality

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#10]
Kovid

I am testing the following code with my service:

def f():
    for i in range(3):
        yield i

x = [0, 1, 2]
y = [x for x in f()]

print("x : " , x) 
print("y : " , y) 

print( x == y)

Here is the result :+1: 

x :  [0, 1, 2]  
y :  [0, 1, 2] 
False

**Comment by kovidgoyal** [comment]
Read the gotchas section of the readme, about operator overloading. Use the function equals() to compare containers.

**Comment by artyprog** [comment]
Thanks Kovid

**Comment by kovidgoyal** [comment]
Note that as of 0.5.1 the equality operator should work just as in python, with negligible performance loss in the common cases.

**Comment by artyprog** [comment]
Tanks Kévin
