### ISSUE TITLE
startswith and other string methods missing

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#100]
in both the online repl, and using the rapydscript compiler
```
'abc'.startswith('a')  
```
yields
```
TypeError: "abc".startswith is not a function
```
I get similar errors for other string functions including isupper and replace.

This is odd, because it does work in glowscript.  
see also https://github.com/kovidgoyal/rapydscript-ng/issues/51

**Comment by jonschull** [comment]
(I'd like it available in Rapydscript so I can write javascript functions independent of vpython)

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/rapydscript-ng#strings
