### ISSUE TITLE
Slowness with Python dictionaries

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#101]
Kovid, I wanted to use "from __python__ import dict_literals, overload_getitem" to make dictionaries have the same properties as in CPython. However, I find that the performance hit is huge. A particularly computationally-intensive user program is a factor of 6 slower when I do the import. From that user program, here is the Python statement and the corresponding JavaScript statements without and with Python dictionaries:

vx[i] *= 1.1 # vs is a list

vx[(typeof i === "number" && i < 0) ? vx.length + i : i] = vx[(typeof i === "number" && i < 0) ? vx.length + i : i] * 1.1;

RS_setitem(vx, i, RS_getitem(vx, i) * 1.1);

I realize that you must have to execute a lot of code to make dictionaries behave in a way unnatural for JavaScript, so maybe I simply cannot turn on Python dictionaries. I'm showing you this data in the forlorn hope that you see some way around this.

**Comment by kovidgoyal** [comment]
Yeah, there isn't a way to fix that. It's why they aren't turned on by default. Basically, in a python dict item access/setting/testing happens through function calls (__getitem__/__setitem__/__contains__). Whereas with a JS object, item access can be optimized by the JIT compiler to be a direct hash table lookup, which is much faster.
