### ISSUE TITLE
__call__ 

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#106]
Does rapydscript provide a method for making a class callable?

In python, __call__ does the trick:
```
class test():
    def __call__(self,*args, **kwargs):
        print('__call__ was called', args, kwargs)
    
t=test()
t.__call__('arg1', a=1)  #works 
t('arg2', b=2)             #fails with rapydscript:
```
Here's the output message I get under the r[apydscript REPL ](https://kovidgoyal.github.io/rapydscript/repl/)
```
__call__ was called ["arg1"] {"a":1}
TypeError: f.apply is not a function
```

**Comment by kovidgoyal** [comment]
No, it doesn't. There is no nice way to implement this in ES5 as far as I know. You can mock it using bind, something like:

```py
t = test()
t = t.__call__.bind(t)
```
