### ISSUE TITLE
__setattr__ or equivalent

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#109]
Is there a way to modify  a class's setattribute behavior?

in python, this code modifies  what happens when I set an attribute.
In rapydscript, not:

```
class test():
    def __init__(self):
        self.test='init'

    def __setattr__(self, k, v):  ## this is ignored in rapydscript but invoked in python
        v=v*10  #this is the modification
        print('setattr invoked:', k, '=', v)
        dict.__setattr__(self,k,v)
 
t=test()
t.a='!'
print('t.a.=', t.a)
```

rapydscript output: 
```
>>>t.a.= !
```
python output:
```
>>>setattr invoked: test = initinitinitinitinitinitinitinitinitinit
>>>setattr invoked: a = !!!!!!!!!!
>>>t.a.= !!!!!!!!!!
```

**Comment by kovidgoyal** [comment]
No, just as with `__call__` there is no way to do that. It would require operator overloading, in this case the . operator which RS does not do, for performance reasons.
