### ISSUE TITLE
Redirecting errors

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#11]
Hy Kovid,

Is there a way to capture error messages when compiling, in order to display them on Javascript side ?

Regards

**Comment by kovidgoyal** [comment]
Redirect stderr

**Comment by artyprog** [comment]
Here is what i have done

 proc=subprocess.Popen(['./rapydscript'],stdin=subprocess.PIPE,stdout=subprocess.PIPE)
 proc.stdin.write(wsock.receive())
 out,err=proc.communicate()
 wsock.send(out)

 I can't catch compiler errors...

**Comment by kovidgoyal** [comment]
compiler errors are in err, not out and you forgot to redirect stderr in your call to Popen

**Comment by artyprog** [comment]
I am trying  this one.
Nothong more on console, but I can't read the errors in proc.stderr.read()

proc=subprocess.Popen(['./rapydscript'],stdin=subprocess.PIPE,stdout=subprocess.PIPE, stderr=subprocess.PIPE)

proc.stdin.write(wsock.receive())

out,err=proc.communicate()

wsock.send(out)

**Comment by artyprog** [comment]
I have managed successfully with popen2.popen3
Thanks Kovid
