### ISSUE TITLE
Support for await / async

### ISSUE THREAD

**Issue by icarito** [kovidgoyal/rapydscript-ng#111]
I think this should be possible?

Possibly look at transcrypt's implementation for inspiration: https://github.com/QQuick/Transcrypt/issues/131

This would help in using some JS APIs in a more pythonic fashion.

**Comment by kovidgoyal** [comment]
I'm not a particular fan of async/await (I find callbacks to be perfectly acceptable for my needs). Not to mention that currently rapydscript targets ES5 by default where this is not possible. But, I have no objections to a PR adding this support.

**Comment by icarito** [comment]
I see your point, this is after all a kind of advanced feature. Thanks for considering it.
