### ISSUE TITLE
"-import-path option to the RapydScript compiler"

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#112]
The Readme makes reference to an --import-path option
`RAPYDSCRIPT_IMPORT_PATH environment variable or the --import-path option to the RapydScript compiler. See the documentation of the option for details.`
-- https://github.com/kovidgoyal/rapydscript-ng/blob/master/README.md#modules 

But I can't find documentation of the option, and 
`rapydscript --import-path`

returns 
`The option: --import-path is not recognized`

help?

**Comment by kovidgoyal** [comment]
rapydscript compile --import-path
