### ISSUE TITLE
how to "import" from a javascript library

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#113]
WIthin the REPL, or in a pyj file, is it possible to import and use the functionality of a third party library?

(I've read the documentation on @external and see discussions of sprintf...but it's over my head.)

Could you provide a snippet?

**Comment by kovidgoyal** [comment]
No import only works with rapydscript files. You can use javascript libraries just as you would in a javascript project. javascript libraries typically install them into the global namespace, from where you can call them in rapydscript just as you call them in javascript.

**Comment by jonschull** [comment]
Thanks.  I understand how to do this in the browser. 

But how do I "use" a javascript library outside of the browser, e.g., when using rapydscript -x ?

I suspect the answer has to do with "require", but haven't been able to get it to work.  Can it work? Snippet?
