### ISSUE TITLE
Please point to `virtual filesystem interface`

### ISSUE THREAD

**Issue by icarito** [kovidgoyal/rapydscript-ng#114]
Hi Kovid!
The solution I took before (#61) was fine for importing files only in the browser. But our IDE is growing and now we support persistent remote file using WebDAV. In my current solution only files previously open in the editor are importable.

I'd like to take you up on:
> Ah, well it's a while since I looked at that part of the code, but basically, the compiler has a completely virtual filesystem interface. You just need to provide it with a readfile() and writefile() function to enable importing. That is how importing the standard library (for e.g. import re) works in the browser compiler. If you look at the commit where I added that functionality it might give you some clues as to how to make it more general.

Could you please point me to where I could implement those readfile and writefile mechanisms? I was a little bit lost. Maybe I can make something that will be useful for others too. Thank you!

**Comment by kovidgoyal** [comment]
You just need to change the implementation of readFileSync and writeFileSync in web-repl/env.js to use hwatever mechanism you like to get the data. The only limitation is that it is a synchronous API.
