### ISSUE TITLE
type of kwargs is "undefined" within a class

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#115]
WITHDRAWN.  I think I just (rediscovered) that RS just doesn't support args and kwargs in clases

The type statement doesn't know what to make of kwargs.
(it returns type(kwargs)  returns "undefined"

That's a bug, I presume.

I also presume the answer is "Object" rather than dict [which was my assumption], because I can access members, even though I can't access kwargs.items() 

```
class X():
    def __init__(self, *args, **kwargs):
        print(kwargs, type(kwargs)) # type is "undefined"
        for kwarg in kwargs:
            print( kwarg,kwargs[kwarg] )
        print(kwargs.items()) #fails because kwargs.items is not a function
        
X(a=1, b=2) #X prints value,  and we can access kwargs[kwarg] but type is #undefined

```

**Comment by kovidgoyal** [comment]
Everything (other than primitives) in javascript is an object. That includes kwargs. In RS kwargs has no well defined type, it is not a dict, RS dicts are (by default) not python dicts, for performance reasons. I dont recall why type(kwargs) is undefined, but it is supported in classes. Runnign your example, deleteing the call to items gices me the output
```
{"a":1, "b":1} undefined
a 1
b 1
```
