### ISSUE TITLE
embedded compiler

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#117]
In the embedded compiler, you can not instantiate a class defined elsewhere, 
even though you can access an instance defined elsewhere.

Elsewhere, I find that GlowScript objects _can_ be instantiated in the embedded compiler, and their attributes _can_ be accessed.  But the object-instance itself is undefined, and this causes trouble.

This is illustrated in the attached image and HTML file.
(The example  uses two embedded compilers, but I get the same pattern when I include compiled js using script tags.)

So I'm hoping you can tell me how to make classes defined outside of an embedded compiler could be made instantiatable in the embedded compiler.

And it would be nice if instantiated objects were always defined.

![pasted_image_5_14_18__7_58_pm](https://user-images.githubusercontent.com/53673/40029214-4113212e-57b1-11e8-817f-e5aaa024e71a.jpg)

[barebones.html.txt](https://github.com/kovidgoyal/rapydscript-ng/files/2002981/barebones.html.txt)

**Comment by kovidgoyal** [comment]
As far as I know that is not possible. The best you can so is use @external to mock class definitions from places other than the rapydscript scource.
