### ISSUE TITLE
File watcher Support

### ISSUE THREAD

**Issue by devxpy** [kovidgoyal/rapydscript-ng#118]
This would be a great addition.

Moreover, if we could make this  a webpack plugin, don't even have to watch the files, and it would also make it easier to Integrate it in the existing workflow.

**Comment by kovidgoyal** [comment]
I'm not sure I understand what this has to do with rapydscript? File watching is typically an OS/runtime feature, not language feature. So in a browser you cannot have a file watcher regardless of what language you use.  If you are running on node, you can use the fs.watch package just as you would from javascript.
