### ISSUE TITLE
.bind() fails with SyntaxError: "Unexpected token ;" 

### ISSUE THREAD

**Issue by ralphwetzel** [kovidgoyal/rapydscript-ng#120]
Hi!
Test case ...

```
>>> def f():
...     return 1
... .bind(this)
```

... results in:

```
---------- Compiled JavaScript ---------
(function f() {
    return 1;
};
).bind(this);
---------- Running JavaScript ---------
<repl>:3
};
 ^

SyntaxError: Unexpected token ;
    at [...]
```
Even worse:

```
>>> def f(arg):
...     return arg
... .bind(this)
... 
... 
---------- Compiled JavaScript ---------
(function f(arg) {
    return arg;
};
if (!f.__argnames__) Object.defineProperties(f, {
    __argnames__ : {value: ["arg"]}
});
).bind(this);
---------- Running JavaScript ---------
<repl>:3
};
 ^

SyntaxError: Unexpected token ;
    at [...]
```
... creates this issued ';' twice (lines 3 & 6).

Is this an issue in the compiler or my wrong application of the `.bind()` feature?

BR, Ralph

**Comment by kovidgoyal** [comment]
It will work only with anonymous functions. If you think about it it only makes sense with anonymous functions. So
```py
def (x):
   return x
.bind(10)
```

should be fine. 

I should note that this feature (block chaining) is really a holdover from the original rapydscript that I am not a fan of.
