### ISSUE TITLE
Anonymous function as Class Variable: Collisions due to created `prototype`definitions?

### ISSUE THREAD

**Issue by ralphwetzel** [kovidgoyal/rapydscript-ng#121]
Consider the following class definition:
```
>>> class test():
...     f = def(data):
...         lines = data.join(" ")
...         print(lines)
...         
...     def lines(self, value):
...         print(value)
```

`f` shall be a function defined as 'class variable'. Intension is to later refer to this function as `test.f`.
This compiles to:
```
function test() {
    if (this.ρσ_object_id === undefined) Object.defineProperty(this, "ρσ_object_id", {"value":++ρσ_object_counter});
    test.prototype.__init__.apply(this, arguments);
}
test.prototype.__init__ = function __init__ () {
    };
test.prototype.lines = function lines(value) {
    var self = this;
    print(value);
};
if (!test.prototype.lines.__argnames__) Object.defineProperties(test.prototype.lines, {
    __argnames__ : {value: ["value"]}
});
test.prototype.__repr__ = function __repr__ () {
        return "<" + __name__ + "." + this.constructor.name + " #" + this.ρσ_object_id + ">";
};
test.prototype.__str__ = function __str__ () {
    return this.__repr__();
};
Object.defineProperty(test.prototype, "__bases__", {value: []});
test.prototype.f = (function() {
    var ρσ_anonfunc = function (data) {
        var lines;
        test.prototype.lines = data.join(" ");
        print(test.prototype.lines);
    };
    if (!ρσ_anonfunc.__argnames__) Object.defineProperties(ρσ_anonfunc, {
        __argnames__ : {value: ["data"]}
    });
    return ρσ_anonfunc;
})();

```
It's not obvious at first glance, yet this creates several definitions of `test.prototype.lines`, one for the `lines`variable in `f = def(data)`, one for `def lines(value)`.

In reality, the compiler creates one `test.prototype.[...]`entry for each **variable** defined in any anonymous function!

As those variables are exclusively used within the function: Why is it necessary to create a `prototype`definition for each of them?
How can I prevent the collisions that happen with this pattern?

**Comment by kovidgoyal** [comment]
If you want to create staticmethods use the @staticmethod decorator, just as you would in python. This is indeed a bug int he compiler, but not one I am very interested in fixing, since I can't think of any useful use case for assiging anonymous functions to class variables. Use @staticmethod instead.
