### ISSUE TITLE
Pythonizing NaN?

### ISSUE THREAD

**Issue by ralphwetzel** [kovidgoyal/rapydscript-ng#122]
I'm fully aware that (Standard) Python does not know `NaN` while JS does.

Consequentially I (think I) have to use `isNaN(f)` in RapydScript - despite it's missing the Python like elegance.
I would prefer to work with `NaN` as I do with `None`: `if f is NaN` feels like a very straight forward way of operation.
Have you thought about this feature? Any chance you might consider implementing it?

**Comment by ralphwetzel** [comment]
Thank you for your fast response & implementation! :thumbsup:

Just a note: The way this check is implemented creates different results than `isNaN(...)`: 
- `isNan(...)` first tries to cast the argument to `Number` and then compares the result vs. `NaN`.
- With `... is <not> NaN` (as implemented) there's no cast operation - thus the results may differ.

Do I consider the implementation being correct? Yes I do - as we explicitly check for `NaN` yet any (other = casted) value.

**Comment by kovidgoyal** [comment]
Yes, IMO this way of testing for NaN is the best, see for example http://adripofjavascript.com/blog/drips/the-problem-with-testing-for-nan-in-javascript.html
