### ISSUE TITLE
How to enable function annotation & compile time or run time type mismatch detection?

### ISSUE THREAD

**Issue by ralphwetzel** [kovidgoyal/rapydscript-ng#126]
Hi!
I tried to work with static typing using the "function annotation" feature. Test case:
```
class Tester():

    def test(self, x: Number) -> Number:
        return "Hallo"

    def run_test(self):
        t = "Test"
        return self.test(t)
```

According to my expectations, this code should raise at least two compile time errors ...
... as `test` returns a `string`, yet the typing declares it shall return a `Number`.
... as `run_test` calls `test` with an argument of type `string`, whereas the typing expects (again) a `Number`.

Instead, invoking `rapydscript compile source/__init__.pyj --output source/index.js -m` compiles fine & creates the following code:

```
(function(){
    "use strict";

    (function(){

        var __name__ = "__main__";


        function Tester() {
            if (this.ρσ_object_id === undefined) Object.defineProperty(this, "ρσ_object_id", {"value":++ρσ_object_counter});
            Tester.prototype.__init__.apply(this, arguments);
        }
        Tester.prototype.__init__ = function __init__ () {
                    };
        Tester.prototype.test = function test(x) {
            var self = this;
            return "Hallo";
        };
        if (!Tester.prototype.test.__annotations__) Object.defineProperties(Tester.prototype.test, {
            __annotations__ : {value: {x: Number, return: Number}},
            __argnames__ : {value: ["x"]}
        });
        Tester.prototype.run_test = function run_test() {
            var self = this;
            var t;
            t = "Test";
            return self.test(t);
        };
        Tester.prototype.__repr__ = function __repr__ () {
                        return "<" + __name__ + "." + this.constructor.name + " #" + this.ρσ_object_id + ">";
        };
        Tester.prototype.__str__ = function __str__ () {
            return this.__repr__();
        };
        Object.defineProperty(Tester.prototype, "__bases__", {value: []});

    })();
})();
```

It looks as if there's a provision for typing generated - the `Tester.prototype.test.__annotations__ ` sequence - yet no code to perform any run-time type checking. Thus there's neither compile time nor run time type checking capability engaged.

Perhaps I am missing something obvious. What do I have to do / enable / change, to operate with the typing capabilities "advertised"?

**Comment by kovidgoyal** [comment]
rs-ng has no typing capabilities. IIRC they were added to the original rapydscript after the fork and I have not bothered porting it, as I am not a fan of typiing.

**Comment by kovidgoyal** [comment]
Not something I am interested in personally. Patches are welcome. I maintain several huge projects, never yet felt the need for typing.
