### ISSUE TITLE
5e-2 does not compile

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#13]
Thanks for pointing me to the information on how to embed the compiler, which worked instantly with some rather complex existing programs. There is a bug in compiling exponential-format numbers. If the exponent is negative, as in 5e-2 or 5E-2, there is a compile error (positive exponents are handled correctly):

Failed to compile RapydScript with error:
Invalid syntax: 5E
☛ a = 5E-2
☛     ⬆

And a quick question: Is something like stdlib already included in the embedded compiler, or do I need some other files from rapydscript-ng?

**Comment by kovidgoyal** [comment]
The RS-ng stdlib, i.e. all modules in src/lib are available in the
embedded RS.

**Comment by BruceSherwood** [comment]
I gather that the embedded RS has not been updated to fix 5E-2. I would appreciate having the fix, or alternatively perhaps you could document how to produce the embedded RS from the files in rapydscript-ng? Thanks.

**Comment by kovidgoyal** [comment]
It has been updated. And if you want to produce it yourself, simply run the bin/export-web-repl tool as I described earlier.

**Comment by BruceSherwood** [comment]
Great! Thanks much.
