### ISSUE TITLE
How to import across directories?

### ISSUE THREAD

**Issue by ralphwetzel** [kovidgoyal/rapydscript-ng#131]
This is more a question rather than an issue:
**What's necessary to import a module located in a separate directory tree?**

The directory structure of a small example::
<img width="189" alt="image" src="https://user-images.githubusercontent.com/16342003/56439606-f097ef80-62e6-11e9-80e1-20163a23bb67.png">

`app/__init__.pyj`:
```
from control import TestA
class TestApp():
    def __init__(self):
        self.control = TestA()
```
`control/__init__.pyj`:
```
class TestA():
    def __init__(self):
        pass
```
The command line:
`rapydscript compile aa/app/__init__.pyj --output aa/test.js --import-path aa/control`

This results in the following error:
`aa/app/__init__.pyj:Failed Import: 'control' module doesn't exist in any of the import directories: aa/control:/[...]/node_modules/rapydscript-ng/src/lib:aa/app (line: 1, col: 13, pos: 13)`

What am I missing here?

**Comment by kovidgoyal** [comment]
Import path needs to be the path to the directory containing the
folder that contains __init__.pyj

And it can contain multiple directories, if needed. In your example,
you would need it to be aa not aa/control

**Comment by ralphwetzel** [comment]
:+1:
Thank you!
