### ISSUE TITLE
import within module

### ISSUE THREAD

**Issue by ralphwetzel** [kovidgoyal/rapydscript-ng#132]
Another question regarding the `import` logic:
Continuing the example in #131, there's now an `item` (component) within the `control` module. `control` intends to `import` from `item`. 

<img width="189" alt="image" src="https://user-images.githubusercontent.com/16342003/56461772-6d46ce80-63b8-11e9-852b-4311747095b5.png">

`control/__init__.pyj`:
```
from item import Item

class TestA():
    def __init__(self):
        i = Item()
        pass
```

`control/item.pyj`:

```
class Item():
    def __init__(self):
        pass
```
Thanks to #131 I can make this compile with the following command line:
`rapydscript compile aa/app/__init__.pyj --output aa/test.js --import-path aa:aa/control`. `item.pyj` yet is only found due to the additional `--import-path` definition of **aa/control**, extending the search path to the next deeper directory level. It works - yet it's very inconvenient (at least from my point of view).

I tried other option to build the import statement:
`from control.item import Item` returns `Detected a recursive import of: control while importing: control (line: 1, col: 18, pos: 18)`.

`from .item import Item` returns `Unexpected token: punc «.» (line: 1, col: 5, pos: 5)`.

Therefore there seems to be no option to `import` within a directory, if this is not at the first level of the `--import_path`. Do you confirm this?

If you do, I'd propose to alter `do_import` to *not emit* an `import_error` in case it detects a recursion (which isn't any in that case), but just `return;`:

https://github.com/kovidgoyal/rapydscript-ng/blob/5d0b95e243fe2e6f53e35266d6d20332d2a505a7/src/parse.pyj#L710-L714

**Comment by kovidgoyal** [comment]
Dont put your code in control/__init__.pyj put it in
control/something.pyj and leave control/__init__.pyj as an empty
placeholder. In control/__init__.pyj you cannot import code from other
modules/packages inside control, since that requires control to be
imported first, which means control/__init__.pyj has to be imported.
