### ISSUE TITLE
Compilation error @ Literal JavaScript

### ISSUE THREAD

**Issue by ralphwetzel** [kovidgoyal/rapydscript-ng#136]
`t = v'"\\test"'` becomes `t = "\test"` after compilation ... erroneously stripping one of the `\`.

**Comment by kovidgoyal** [comment]
That is correct. In python, and therefore RS string literals, backslases
need to be escaped. A literal is also a string literal, so

v'"a\\x"'

is the same as

'"a\\x"'

and is a followed bya  single backslash followedby x
