### ISSUE TITLE
Lambda functions

### ISSUE THREAD

**Issue by kakaroto** [kovidgoyal/rapydscript-ng#141]
I love rapydscript, thanks for doing this! One issue I have is with how "hard/ugly" it is to make small anonymous functions (especially since emacs doesn't like to indent it propertly when they are within an argument list). I'd like to be able to define an anonymous function on one line.
Would it be possible to add support for lambda functions ? Something like this : 
```
setTimeout(lambda: self.timeout(arg), 1000)
```
Instead of having to do : 
```
setTimeout(def():
                        self.timeout(arg)
                   , 1000)
```
It would be a great feature, like how ES6 introduced arrow functions.

**Comment by kovidgoyal** [comment]
```py

def myfunc(): whatever;
```

**Comment by kakaroto** [comment]
Ah, stupid me, thanks, I hadn't realized I could use the semicolon to terminate the function. That's great!
