### ISSUE TITLE
How to run this code in Rapdyscript-NG

### ISSUE THREAD

**Issue by RyanBram** [kovidgoyal/rapydscript-ng#144]
Hi.
I am a beginner Python learner.
I am practicing this tutorial: https://inventwithpython.com/
But when I trying to translate a script to javascript using Rapydscript-NG the following error appear:
`ReferenceError: input is not defined`

How to use `input()` properly in Rapydscript-NG?
Anyway, this is the script: 
```
import random

print ("Hello, I am your PC.")
print ("Can you tell me what's your name?")

userName = input()

print ("Okay, so your name is " + userName)

secretNumber = random.randint (1, 20)

print ("Hi " + userName + ". I have  a number.")
print ("The number is between 1 until 20")
print ("Can you guess it?")

chance = 0

for chance in range (6):
    print ("Please take a guess.")
    guess = input()
    guess = int(guess)

    if secretNumber < guess:
        print ("Your number is too high")
    if secretNumber > guess:
        print ("Your number is too low")
    if secretNumber == guess:
        break
	
if secretNumber == guess:
    print ("Wow, nice! You successfully guess my secret number in " + str(chance + 1) + " chance.")

if secretNumber != guess:
    print ("Hmm, sorry my secret number is " + str(secretNumber) + ".")

```

**Comment by kovidgoyal** [comment]
input() is a function used to get input from the user with a controlling
terminal. Rapydscript is mostly used to run in browsers, where there is
no terminal. Hence there is no such function. You can use various
browser APIs to get input from the user, or if you are writing a program
to run in the terminal with Node, then node hs APIs you canuse for this
purpose.
