### ISSUE TITLE
string replace

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#150]
A GlowScript reported, corrrectly, this bug:

print("hat hat hat".replace("hat","tree")) only returns "tree hat hat", with only the first occurrence of hat replaced by tree. In other versions of python the replace function replaces all occurrences.

**Comment by kovidgoyal** [comment]
Yes, that's because it is the JavaScript replace function. RapydScript
by default does not override JS functions so as to interoperate. https://github.com/kovidgoyal/rapydscript-ng#strings

**Comment by BruceSherwood** [comment]
Understood. Obviously I failed to search your documentation. I solved my problem (where Python takes precedence over interoperability with JavaScript) by creating a new GSrep function that replaces all instances in the string, and I replace user programs' use of .replace with .GSrep.
