### ISSUE TITLE
super()?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#151]
The following works, but If I try to use super() instead of Ball I get "Error: super is a reserved word". Is this a bug?

`class Ball:
    def __init__(self):
        print('Ball init')

class Orb(Ball):
    def __init__(self):
        print('Orb init')
        #super().__init__()
        Ball.__init__()
        
ball = Orb()`

**Comment by BruceSherwood** [comment]
I try again to insert code with tabs:

`class Ball:
    def __init__(self):
        print('Ball init')

class Orb(Ball):
    def __init__(self):
        print('Orb init')
        #super().__init__()
        Ball.__init__()
        
ball = Orb()`

**Comment by BruceSherwood** [comment]
Odd; code insertion fails. Dunno what I'm doing wrong here. Sorry.

**Comment by kovidgoyal** [comment]
super is not supported in RS as it is a keyword in javascript with
different semantics. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super
