### ISSUE TITLE
Decorate problem

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#153]
I'm sorry to trouble you with a problem with decorate not working, since it seems likely that I'm doing something wrong, but maybe you can tell me what my mistake is. Here is a Python program, followed by the output at your REPL. After that is what I'm getting as output from the latest version of the embedded compiler, which is the same that I got with an earlier version. You'll see that the embedded compiler version is missing key elements of the decoration machinery, and it adds some additional elements ( __module__ : {value: "__main__"}). All other aspects of the embedded installer work; I'm only having difficulty with decorate. I call the compiler with compile(input, {js_version:6}), but it's no different if I call compile(input).

I built the embedded compiler following your instructions, as I've always done.

def deco(func):
    def wrap(*args, **kwargs):
        print('before')
        func(*args, **kwargs)
        print('after')
    return wrap

@deco
def foo(s):
    print('foo', s)
    
---------------------------------

function deco(func) { // REPL
    function wrap() {
        var kwargs = arguments[arguments.length-1];
        if (kwargs === null || typeof kwargs !== "object" || kwargs [ρσ_kwargs_symbol] !== true) kwargs = {};
        var args = Array.prototype.slice.call(arguments, 0);
        if (kwargs !== null && typeof kwargs === "object" && kwargs [ρσ_kwargs_symbol] === true) args.pop();
        print("before");
        ρσ_interpolate_kwargs.call(this, func, args.concat([ρσ_desugar_kwargs(kwargs)]));
        print("after");
    };
    if (!wrap.__handles_kwarg_interpolation__) Object.defineProperties(wrap, {
        __handles_kwarg_interpolation__ : {value: true}
    });

    return wrap;
};
if (!deco.__argnames__) Object.defineProperties(deco, {
    __argnames__ : {value: ["func"]}
});

var foo = deco((function() {
    var ρσ_anonfunc = function foo(s) {
        print("foo", s);
    };
    if (!ρσ_anonfunc.__argnames__) Object.defineProperties(ρσ_anonfunc, {
        __argnames__ : {value: ["s"]}
    });
    return ρσ_anonfunc;
})());

foo("bar");
    
---------------------------------

function deco(func) {
    function wrap() {
        var kwargs = arguments[arguments.length-1];
        if (kwargs === null || typeof kwargs !== "object" || kwargs [ρσ_kwargs_symbol] !== true) kwargs = {};
        var args = Array.prototype.slice.call(arguments, 0);
        if (kwargs !== null && typeof kwargs === "object" && kwargs [ρσ_kwargs_symbol] === true) args.pop();
        print("before");
        ρσ_interpolate_kwargs.call(this, func, args.concat([ρσ_desugar_kwargs(kwargs)]));
        print("after");
    };
    if (!wrap.__handles_kwarg_interpolation__) Object.defineProperties(wrap, {
        __handles_kwarg_interpolation__ : {value: true},
        __module__ : {value: "__main__"}
    });

    return wrap;
};
if (!deco.__argnames__) Object.defineProperties(deco, {
    __argnames__ : {value: ["func"]},
    __module__ : {value: "__main__"}
});

function foo(s) {
    print("foo", s);
};
if (!foo.__argnames__) Object.defineProperties(foo, {
    __argnames__ : {value: ["s"]},
    __module__ : {value: "__main__"}
});

foo("bar");

**Comment by kovidgoyal** [comment]
Sorry, it's been rather too long since I have looked at this codebase. Nothing pops out to me off the top of my head for why a decorator would not work with the embedded compiler. I'd have to trace the code, and I dont have the time to do that at the moment.

**Comment by kovidgoyal** [comment]
And it works fine for me with:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Test embedded RapydScript</title>
        <script charset="UTF-8" src="https://sw.kovidgoyal.net/rapydscript/repl/rapydscript.js"></script>
        <script>
var compiler = RapydScript.create_embedded_compiler();
var js = compiler.compile(`
def deco(f):
    def wrap(*a, **kw):
        print('defore decorated call')
        f(*a, **kw)
        print('after decorated call')
    return wrap

@deco
def test():
    print('in decorated call')
test()
`);
window.onload = function() {
    document.body.textContent = js;
    eval(js);
};
        </script>
    </head>
    <body style="white-space:pre-wrap"></body>
</html>
```

**Comment by BruceSherwood** [comment]
Thanks. Somehow you laying it out like that stimulated me to look in a different part of my code, and now I see my mistake.
