### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by ese942** [kovidgoyal/rapydscript-ng#156]
Hi, this looks like a great project, very impressive.  Particularly the readme documentation - very thorough introduction.

I don't see a discussion group or mailing list, so forgive me for asking a few questions  here:

1) What's the best way to achieve maximum python compatibility?  I saw the import pythonize lines in the readme.  Are there are any more options like this?  I have existing python code I want to port, max compatibility would make it easier.  E.g. empty dict / array truthiness, list addition, string [ ] behavior, etc.

2) Is there any equivalent for f-strings?  Didn't see them mentioned.

3) Where else should I look to learn more about rapydscrypt?  Is there any other documentation?  Is there a discussion group or mailing list anywhere?

 Thanks.  Best of luck with this fantastic project.

**Comment by kovidgoyal** [comment]
You can use the discussions in github itself https://github.com/kovidgoyal/rapydscript-ng/discussions

1) pythonize and `from __python__` search the readme for these two.

2) f-strings are supported

3) I'm afraid the readme is it
