### ISSUE TITLE
Import problem?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#160]
Sometime in the last year or so I apparently made a mistake in performing an update to RapydScript, because "import random" now gives "Error: Failed import 'random' module doesn't exist in any of the import directories: __stdlib__". I didn't notice this until recently because very few GlowScript VPython users use this feature. I assume it's my fault, because "import random" works fine in the REPL. Nevertheless, do you have any insight into how I might have gone wrong? Thanks.

**Comment by kovidgoyal** [comment]
No clue, sorry. Does it work in the demo online REPL? If so, just use
the build from there.

**Comment by BruceSherwood** [comment]
As I said, it does indeed work in your REPL. Where do I find the documentation on how to build the REPL?

**Comment by BruceSherwood** [comment]
Oh, I guess I found the compiler I need: https://sw.kovidgoyal.net/rapydscript/repl/rapydscript.js. Is this up-to-date?

**Comment by kovidgoyal** [comment]
On Sat, Jan 30, 2021 at 04:35:11PM -0800, BruceSherwood wrote:
> Oh, I guess I found the compiler I need: https://sw.kovidgoyal.net/rapydscript/repl/rapydscript.js. Is this up-to-date?

Yes, it is, and the documentation for how to build it is in the README
