### ISSUE TITLE
class decorator bug

### ISSUE THREAD

**Issue by valq7711** [kovidgoyal/rapydscript-ng#161]
Hello Kovid!
Just yesterday I fixed Rapydscript class decorator bug (it was wrong decorators calls order). I took a look at implementation in your fork. It looks like things are even worse here;)
As you can see, decorator gets `'dummy'`  constructor
```python
def decor(a):
    return a

@decor
class A:
    @decor
    def foo(self):
        pass
```

```javascript
function decor(a) {
    return a;
};
if (!decor.__argnames__) Object.defineProperties(decor, {
    __argnames__ : {value: ["a"]}
});


var A = decor(function A() {
    if (this.ρσ_object_id === undefined) Object.defineProperty(this, "ρσ_object_id", {"value":++ρσ_object_counter});
    A.prototype.__init__.apply(this, arguments);
});
A.prototype.__init__ = function __init__ () {
    };
A.prototype.foo = decor(function foo() {
    var self = this;
});
A.prototype.__repr__ = function __repr__ () {
        return "<" + __name__ + "." + this.constructor.name + " #" + this.ρσ_object_id + ">";
};
A.prototype.__str__ = function __str__ () {
    return this.__repr__();
};
Object.defineProperty(A.prototype, "__bases__", {value: []});
```

Also keep in mind that there is an edge case like:
```python
@foo.bar()
class A:
    @foo.baz  #  !important: this decorator must be applied **after** `foo.bar()`-call
    def foo(self):
        pass
```

**Comment by kovidgoyal** [comment]
Not clear to me what the bug is?? A class decorator is supposed to decorate a class. Not its __init__ method. If you want to decorate the __init__ method you would decorate it separately.

**Comment by valq7711** [comment]
I mean js-constructor - it has pristine prototype with no methods, i.e. it is empty class

**Comment by kovidgoyal** [comment]
Ah, you mean you expect the class decorator to be called after the class prototype is populated??

**Comment by valq7711** [comment]
Yes

**Comment by valq7711** [comment]
But only decorator itself, decorator 'factory' (like `@foo.bar()`) should be called before
