### ISSUE TITLE
when converting .children() to list, i get list of empty dictionaries

### ISSUE THREAD

**Issue by dewball345** [kovidgoyal/rapydscript-ng#162]
Hello there,

My code is like this

```
elem = document.createElement("div")
elem.appendChild(document.createElement("h1"))
elem.appendChild(document.createElement("h1"))

print(elem.children()[0])
```

I do not get an HTML element, but i get an empty dictionary. Why is this the case?

**Comment by kovidgoyal** [comment]
children is a property not a function.
https://developer.mozilla.org/en-US/docs/Web/API/Element/children

**Comment by dewball345** [comment]
It doesn't work even without parenthesis

**Comment by kovidgoyal** [comment]
WOrks for me.

**Comment by dewball345** [comment]
ok, i will try this time to clone rapydscript-ng instead of npm installing it...
