### ISSUE TITLE
string.split()

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#166]
The following code works very differently in Python and RapydScript:

```
s = "   this is a test string "
t = s.split(' ') # or s.split(' ')
print(len(t))
for w in t:
    print(w)
```
Also, a GlowScript user asked about support for b-strings.

**Comment by BruceSherwood** [comment]
Oops: I meant to say that there is difference from Python whether one says s.split(' ') or s.split().

**Comment by kovidgoyal** [comment]
Yes, Javascript and Python have different split implementations. If you
want to override the JS one, use the strings function, as described in
the readme: https://github.com/kovidgoyal/rapydscript-ng#strings

Note that if you do this then any JS libraries you use could break.

As for b strings, no RS has no support for them, and JS has no native
type for them either.

**Comment by BruceSherwood** [comment]
I do import your python string machinery, but I had failed to notice that your documentation clearly says "split() and replace() are left as the native JavaScript versions".
