### ISSUE TITLE
random.randint tolerates 3rd argument

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#168]
`import random  
y = random.randint(3,44,2)
print(y) `

This should throw an error due to the extra 3rd argument, but it apparently ignores the 3rd argument.

**Comment by kovidgoyal** [comment]
Javascript functions in general tolerate any number of arguments. Adding
argument checking to them all is a big performance hit.

**Comment by kovidgoyal** [comment]
It would require a whole different compiler architecture for that. Not
worth the effort for me, at least.
