### ISSUE TITLE
Using RapydScript-ng in cordova

### ISSUE THREAD

**Issue by mardon86** [kovidgoyal/rapydscript-ng#17]
Hi @kovidgoyal im trying to use rapydscript-ng (embedded) in cordova. It works on browser platform target, but doesnt work on the android platform target.
Here is the code:
![rsng-cordova-01](https://cloud.githubusercontent.com/assets/9649930/14698049/b7151304-07b4-11e6-9733-b2960179eda0.jpg)

It works on both platform if i use the original RapydScript.
Here is the code:
![rsng-cordova-02](https://cloud.githubusercontent.com/assets/9649930/14698051/b9524c9a-07b4-11e6-9703-55c1b9893749.jpg)

How to solve this ? am i missing simething ? Thx.

**Comment by kovidgoyal** [comment]
The rs-ng embedded compiler requires an ES 6 compatible runtime. And generates ES 6 compatible javascript. I assume the android platform is not yet ES 6 capable. In that case you will ot be able to use the embedded compiler, only the full compiler, which generates ES 5 compatible code.

**Comment by CoinBR** [comment]
I guess it would work with [crosswalk](https://crosswalk-project.org/documentation/cordova.html). I'm not sure though.

**Comment by kovidgoyal** [comment]
Actually, the embedded compiler has had the ability to generate ES 5 for a while now (as long as you dont use generators/yield statement

https://github.com/kovidgoyal/rapydscript-ng#embedding-the-rapydscript-compiler-in-your-webpage
