### ISSUE TITLE
distionary += error 

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#171]
from __python__ import dict_literals, overload_getitem
a = {1:10, 2:20}
a[1] += 37

compiles to

var a;
a = (function(){
    var ρσ_d = ρσ_dict();
    ρσ_d.set(1, 10);
    ρσ_d.set(2, 20);
    return ρσ_d;
}).call(this);
ρσ_getitem(a, 1) += 37;

which yields this error in the RS REPL:
ReferenceError: Invalid left-hand side in assignment

It seems to me that what the last line should compile to is

ρσ_setitem(a, 1, ρσ_getitem(a, 1) + 37)

**Comment by kovidgoyal** [comment]
From the README

RapydScript does not implement operator overloading, as method calls in JavaScript are very slow compared to raw operators.

**Comment by BruceSherwood** [comment]
?? I don't see how this has anything to do with operator overloading. The problem is that when using the += or -= operator RS sets the left side of the statement to getitem, but the left side needs to be setitem. I did run this in your REPL to verify that the problem wasn't caused by my own code environment.

**Comment by kovidgoyal** [comment]
In order to do that, RS would need to inspect the operands to the += operator, which means it can use the JS += operator anymore, replacing every use of it with a function call.

**Comment by BruceSherwood** [comment]
I'm sorry, but I still don't understand. ρσ_getitem(a, 1) -= 37 is just wrong, throwing an error due to trying to write to a getitem. Surely this HAS to be expressed as ρσ_setitem(a, 1, ρσ_getitem(a, 1, -( 37))), no matter what the execution-time cost, right? What am I missing? A += or -= statement that doesn't invoke ρσ_getitem needn't invoke a function call, right?

**Comment by kovidgoyal** [comment]
You are missing that in RapydScript there is no operator overloading. So you cannot use operators with anything other than primitive types. If you do, you will get errors at runtime.

**Comment by BruceSherwood** [comment]
But you DO detect that your Python-like dictionary is in play, because you generate ρσ_getitem(...) on the left side of an equation. How is that not simply an error? I do have a workaround; in the pre- and post-processing of the Python code I'll look for ρσ_getitem(...) being assigned a value and make the necessary correction. (And I still fail to see what any of this has to do with operator overloading.)

**Comment by kovidgoyal** [comment]
Ah you are running with 

from __python__ overload_getitem

that will indeed cause this error. Remove that and you will be fine.

**Comment by BruceSherwood** [comment]
Is the documentation on RS dictionaries wrong? I used from __python__ import dict_literals, overload_getitem because that's what the README says to do. When I remove overload_getitem and use from __python__ import dict_literals, I still get the same JavaScript with the same associated error in the RS REPL, namely ReferenceError: Invalid left-hand side in assignment.

**Comment by BruceSherwood** [comment]
I got almost everything working, by transforming ρσ_getitem(a, 1) += 37 to ρσ_setitem(a, 1, ρσ_getitem(a, 1) + 37).

However, I encountered another problem I had to address. The VPython statement

box(texture={'file':textures.stones})

generates the form ρσ_d.set("file", textures.stones), which throws an execution error.
This implies something is wrong with the "set" method.

When I transform this to ρσ_d["file"] = textures.stones, it all works.

**Comment by BruceSherwood** [comment]
Also, in the RS REPL using "python import dict_literals, overload_getitem", update() adds undefined: undefined, independent of the update arguments, and popitem() returns the first rather than the last item.

**Comment by kovidgoyal** [comment]
I cannot replicate update not working
```py
cat /t/test.pyj && rapydscript -x /t/test.pyj                                                                                        
from __python__ import bound_methods, hash_literals, dict_literals, overload_getitem

a = {1:1, 2:2}
a[1] = 3
a[1] += 5
a.update({4: 4})
print(a)
{1: 8, 2: 2, 4: 4}
```

**Comment by BruceSherwood** [comment]
When I run your example on your REPL (without the first line, which I don't understand) I get the error "ReferenceError: Invalid left-hand side in assignment", due to the presence of ρσ_getitem(a, 1) += 5;. In my own environment where I convert the left-side getitem to setitem, update does indeed work properly. What is the meaning of your first line? It is rejected by the REPL.

**Comment by kovidgoyal** [comment]
You need to update RS with the fix

**Comment by BruceSherwood** [comment]
Many thanks for the fix! It's been a while since I last built the runtime file, and it failed. From my notes on how to build it (which I assume I got from you long ago), I executed the following (in fact, I uninstalled and reinstalled node, to make sure it was up to date :

1) Make sure node is installed.
2) In a new folder, execute "npm install rapydscript-ng".
3) Create a file named "input.py" in this folder that contains "a=1".
4) Execute this (modify if not on Windows): node.exe .\node_modules\rapydscript-ng\bin\rapydscript --bare input.py > runtime.js

I get this error:

(base) PS D:\0C\workspace\BuildRapydScriptRunTime> node.exe .\node_modules\rapydscript-ng\bin\rapydscript --bare input.py > runtime.js
D:\0C\workspace\BuildRapydScriptRunTime\node_modules\rapydscript-ng\tools\compile.js:85
                if (!(e instanceof RapydScript.SyntaxError)) throw e;
                                                             ^
ReferenceError: ch is not defined
    at read_while (lib/compiler.js:2118:28)
    at read_num (lib/compiler.js:2133:23)
    at Object.next_token [as input] (lib/compiler.js:2437:28)
    at next (lib/compiler.js:2734:33)
    at maybe_assign (lib/compiler.js:4683:25)
    at expression (lib/compiler.js:4699:24)
    at simple_statement (lib/compiler.js:3167:23)
    at lib/compiler.js:3040:28
    at lib/compiler.js:2797:28
    at Object.<anonymous> (lib/compiler.js:4762:31)
(base) PS D:\0C\workspace\BuildRapydScriptRunTime>

Am I using the wrong procedure? What am I doing wrong?

**Comment by kovidgoyal** [comment]
There has been no release with the fix, you will need to run from
master.

**Comment by BruceSherwood** [comment]
Oh, right. It's been a long while since I last did a complete build, and I failed (I'm told that RapydScript doesn't exist). In my notes I have instructions to paste these lines of code into the start of the runtime file, and I wonder if this is no longer appropriate:

	var ρσ_iterator_symbol = (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") ? Symbol.iterator : "iterator-Symbol-5d0927e5554349048cf0e3762a228256";
	var ρσ_kwargs_symbol = (typeof Symbol === "function") ? Symbol("kwargs-object") : "kwargs-object-Symbol-5d0927e5554349048cf0e3762a228256";
	var ρσ_cond_temp, ρσ_expr_temp, ρσ_last_exception;
	var ρσ_object_counter = 0;

**Comment by kovidgoyal** [comment]
I made a release so you can just use it.

**Comment by BruceSherwood** [comment]
That was very helpful, Kovid. Thank you very much!

**Comment by BruceSherwood** [comment]
I thank you again for all the help you gave me in the goal of supporting Python-style dictionaries. The only missing feature is that the setdefault method doesn't exist, which hardly matters.

I did find something that looks like a bug. Consider this code, where
a is a list of VPython spheres and b is a list of VPython vectors:
```
a = [sphere(), sphere()]
b = [vec(-2,0,0), vec(2,0,0)]
for i in range(2):
    b[i] = b[i] + vec(0,1,0)
    a[i].pos = b[i]
```

RS generates the following code, which works:
```
for (var ρσ_Index1 = 0; ρσ_Index1 < 2; ρσ_Index1++) {
    i = ρσ_Index1;
    ρσ_setitem(b, i, ρσ_getitem(b, i) + vec(0, 1, 0));
    ρσ_getitem(a, i).pos = ρσ_getitem(b, i);
}
```


Now consider this code, with its double equal operators:
```
a = [sphere(), sphere()]
b = [vec(-2,0,0), vec(2,0,0)]
for i in range(2):
    a[i].pos = b[i] = b[i] + vec(0,1,0)
```

RS generates the following code, which throws 
a run-time error (Property 'pos' must be a vector):
```
for (var ρσ_Index1 = 0; ρσ_Index1 < 2; ρσ_Index1++) {
    i = ρσ_Index1;
    ρσ_getitem(a, i).pos = ρσ_setitem(b, i, ρσ_getitem(b, i) + vec(0, 1, 0));
}
```

Perhaps a recursion issue? This works in the absence of 
"from __python__ import dict_literals, overload_getitem"

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/rapydscript-ng/commit/84849ab0e65cffa7f477a72861bfa36a6db7649f
