### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#172]
You've been good about building releases, but I'm puzzled as to why I'm unable to create the embeded compiler myself from master, to get your today's update. I've tried many permutations of "bin/web-repl-export /path/to/export/directory" after successfully creating compiler.js and baselib-plain-pretty.js, following the directions in your README. It looks like I should say "npm bin/web-repl-export /path/to/export/directory", but that doesn't work, either. What am I doing wrong?

**Comment by BruceSherwood** [comment]
Maybe I'm asking the wrong question? Maybe what I need to know is how do you create the contents of the release folder?

**Comment by kovidgoyal** [comment]
Read the publish.py script to see how releases are built.

**Comment by BruceSherwood** [comment]
I ran publish.py with Python 3.8.5 and got this error:

```
Traceback (most recent call last):
  File "D:\0C\workspace\BuildRapydScriptRunTime\rapydscript-ng\publish.py", line 12, in <module>
    subprocess.check_call([os.path.join(base, 'build')])
  File "C:\Users\Bruce\anaconda3\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Bruce\anaconda3\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Bruce\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Bruce\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```
Am I supposed to learn what to do from reading the program? I'm running on 64-bit Windows.

**Comment by kovidgoyal** [comment]
On Fri, Dec 17, 2021 at 06:37:10PM -0800, BruceSherwood wrote:
> Am I supposed to learn what to do from reading the program? I'm running on 64-bit Windows.

yes.

**Comment by BruceSherwood** [comment]
Ah. The problem was that bin/web-repl-export /path/to/export/directory failed on Windows but succeeded on a Mac.
