### ISSUE TITLE
pop for dict, pypop for list

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#173]
Currently with Python-like dictionaries turned on it is the case that pop -> pypop is needed with lists but pop is needed with dictionaries. I guess I need to create a function "pop2" that detects whether to call pypop or pop, but maybe RS should provide such a function? Or am I thinking about this wrong?

I do much appreciate your recent work to improve Python-like dictionaries!

**Comment by BruceSherwood** [comment]
I tried inserting "ρσ_list_decorate.prototype.pop = function(arg) {return this.pypop(arg)}" at the start of the JavaScript code in order to drive pypop, but pypop isn't invoked, which is puzzling. Is it possible that the RS pypop method could be modified to do the right thing for both lists and dictionaries? I've used pypop for years (I convert pop to pypop), but that was before taking advantage of the Python-like dictionaries, which need pop, not pypop.

**Comment by BruceSherwood** [comment]
I found a solution. I convert all occurences of ".pop" to ".pypop" in the Python code and edited the compiler and runtime files to change dict.pop to dict.pypop.

**Comment by BruceSherwood** [comment]
(And similar change to set.pop.)

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/rapydscript-ng#lists

And if you want to override the JS pop method, what you need to do is
Array.prototype.pop = Array.prototype.pypop

**Comment by BruceSherwood** [comment]
Setting Array.prototype.pop is simpler than my kludge but doesn't seem to work for me. In the RS REPL I get an error if I try to run this (and I see a similar error when I try this in my application):

```
from pythonize import strings
Array.prototype.pop = Array.prototype.pypop
a = {1:11, 2:22, 3:33}
b = a.pop(1)
```

**Comment by BruceSherwood** [comment]
Nor does the following work in the REPL:

```
from pythonize import strings
dict.prototype.pop = dict.prototype.pypop
a = {1:11, 2:22, 3:33}
b = a.pop(1)
```

**Comment by kovidgoyal** [comment]
Array.prototype.pop = ρσ_list_pop

**Comment by BruceSherwood** [comment]
Okay, in the REPL that works for lists and sets but not for dicts. Is there a similar simple way to make dicts use pypop?
