### ISSUE TITLE
Remove a list from a list

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#177]
The following program throws an error in the REPL: ValueError: [1, 2, 3] not in list

a = [[1,2,3], 5, 10]
a.remove([1,2,3])
print(a)

Does this make any sense to you? In contrast, print([1,2,3] in a) yields True.

**Comment by BruceSherwood** [comment]
Many thanks, Kovid. How might I know when there is a new build? (I don't know how to do builds myself.)

**Comment by kovidgoyal** [comment]
I dont have any plans to make a new build anytime soon. Instructions for making your own builds are in the readme.

**Comment by BruceSherwood** [comment]
In the readme are instructions for building the standard library, but I'm using the embeddable compiler, and I don't see instructions on how to build that...?

**Comment by BruceSherwood** [comment]
Sorry. I missed the instructions at the end of the section on the embedded compiler.
