### ISSUE TITLE
while/else

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#178]
I had not known of Python's while/else structure, but a Web VPython user reported correctly that RS doesn't recognize it:

```
i = 0
while i < 5:
    print(i)
    i += 1
else:
    print('Printing task is done.')
```

**Comment by ibeatty** [comment]
Ha! Bruce beat me to posting this issue by three minutes. I'm the "Web VPython user" he mentioned.

When  put a while/else construct into a Web VPython 3.2 program on glowscript.org, the error message that results is "Error: Unexpected token: punc «:» at line 9: else:"

If I remove the colon after the `else:` (just to see what happens), I get the very expected error message "Error: Line 9, "else", must include a colon."

HTH // Ian

**Comment by kovidgoyal** [comment]
I'm afraid I dont find for..else or while..else useful enough to bother
implementing. Patches welcome.

**Comment by BruceSherwood** [comment]
Makes sense, Kovid. I don't see any difference between using an else and not using an else.
