### ISSUE TITLE
Large slowdown

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#184]
I don't know whether you still have interest in reports about RS, but: Quite a long time ago "ax[i] += fx" compiled to 
ax[(typeof i === "number" && i["<"](0)) ? ax.length["+"](i) : i]=ax[(typeof i === "number" && i["<"](0)) ? ax.length["+"](i) : i]["+"](fx);
but now compiles to
ρσ_setitem(ax, i, ρσ_getitem(ax, i)["+"](fx));
A Web VPython (GlowScript) user had a large number of such statements, many of them executed constantly. Perhaps due to just-in-time compilation by Chrome, the program ran 5 times slower than before the change. The solution was of course v'ax[i] += fx', but this episode does suggest that it could be useful to have a RS flag that says essentially "don't use getitem".

**Comment by kovidgoyal** [comment]
Still does

```
echo 'ax[i] += fx' | rapydscript -m
(function(){
    "use strict";

    (function(){

        var __name__ = "__main__";


        ax[(typeof i === "number" && i < 0) ? ax.length + i : i] += fx;
    })();
})();
```

You have probably turned on from __python__ import overload_getitem

**Comment by BruceSherwood** [comment]
Thanks much. I should have been able to figure it out for myself....

I did find an error in the handling of dictionaries: dict items should be dict_items( [a,b), (c,d) ] ) but instead has the form dict_keys( ['a,b', 'c,d'] ).

**Comment by kovidgoyal** [comment]
Works fine for me

```
>>> from __python__ import dict_literals, overload_getitem
---------- Compiled JavaScript ---------

---------- Running JavaScript ---------
>>> a = {1:2, 2:3}
---------- Compiled JavaScript ---------
var a;
a = (function(){
    var ρσ_d = ρσ_dict();
    ρσ_d.set(1, 2);
    ρσ_d.set(2, 3);
    return ρσ_d;
}).call(this);
---------- Running JavaScript ---------
ρσ_dict { jsmap: Map(2) { 1 => 2, 2 => 3 } }
>>> a.items()
---------- Compiled JavaScript ---------
a.items();
---------- Running JavaScript ---------
[Map Entries] { [ 1, 2 ], [ 2, 3 ] }
>>> Bye!
```
