### ISSUE TITLE
modules are imported alphabetically instead of in import order

### ISSUE THREAD

**Issue by amitu** [kovidgoyal/rapydscript-ng#22]
If I have a module say vyom/parser.pyj, and if it tries to do `from vyom import utils`, and vyom/utils.pyj exists, I get:

```
20:11:49 watchdog.1    | main.pyj:./vyom/parser.pyj:The symbol "utils" is not exported from the module: vyom (line: 6, col: 0, pos: 76)
20:11:49 watchdog.1    | 
20:11:49 watchdog.1    | Error
20:11:49 watchdog.1    |     at ImportError.__init__ (lib/compiler.js:2490:26)
20:11:49 watchdog.1    |     at ImportError.__init__ (lib/compiler.js:2525:78)
20:11:49 watchdog.1    |     at new ImportError (lib/compiler.js:2521:44)
20:11:49 watchdog.1    |     at import_error (lib/compiler.js:5701:23)
20:11:49 watchdog.1    |     at import_ (lib/compiler.js:5891:33)
20:11:49 watchdog.1    |     at lib/compiler.js:5450:32
20:11:49 watchdog.1    |     at lib/compiler.js:5169:28
20:11:49 watchdog.1    |     at lib/compiler.js:7211:31
20:11:49 watchdog.1    |     at parse (lib/compiler.js:7266:14)
20:11:49 watchdog.1    |     at do_import (lib/compiler.js:5798:21)
20:11:49 watchdog.1    | make[1]: *** [../static/charm.js] Error 1
20:11:49 watchdog.1    | main.pyj:./vyom/parser.pyj:The symbol "utils" is not exported from the module: vyom (line: 6, col: 0, pos: 76)
20:11:49 watchdog.1    | 
20:11:49 watchdog.1    | Error
20:11:49 watchdog.1    |     at ImportError.__init__ (lib/compiler.js:2490:26)
20:11:49 watchdog.1    |     at ImportError.__init__ (lib/compiler.js:2525:78)
20:11:49 watchdog.1    |     at new ImportError (lib/compiler.js:2521:44)
20:11:49 watchdog.1    |     at import_error (lib/compiler.js:5701:23)
20:11:49 watchdog.1    |     at import_ (lib/compiler.js:5891:33)
20:11:49 watchdog.1    |     at lib/compiler.js:5450:32
20:11:49 watchdog.1    |     at lib/compiler.js:5169:28
20:11:49 watchdog.1    |     at lib/compiler.js:7211:31
20:11:49 watchdog.1    |     at parse (lib/compiler.js:7266:14)
20:11:49 watchdog.1    |     at do_import (lib/compiler.js:5798:21)
20:11:49 watchdog.1    | make[1]: *** [../static/charm.js] Error 1
```

If I import vyom.parser from vyom/utils.pyj, it works well. If I do not do such imports, and look at generated code, both utils and parser are included, and from other modules I can import both. They are defined in alphabetical order in the compiled js file, so I can see why it is failing. 

I could have lived with this, but even if I try to import inside a function, instead of global import, which is the goto solution for circular import problems in regular python, even then it complains and fails.

May be at import time we should not check for other modules, which should only have one side effect: inability to decide if foo() is a function call or class declaration. I suggest we live with that, remove the check if module exists or not, and I can explicitly write `new foo()` when needed.

**Comment by kovidgoyal** [comment]
utils is not a symbol in vyom/__init__.pyj which is why you get that error. It has nothing to do with circular imports. If you want to import the vyom.utils module as a module, you do:

```py
import vyom.utils as utils
```

This is a difference from the way that imports in python work -- a consequence of the fact that in rs-ng importing is compile time, while in python importing is run time. 

As for circular imports -- those indicate poor code design. I am not going to hobble rs-ng to support them. A circular import is an indication that code needs to be refactored.

**Comment by kovidgoyal** [comment]
I changed the import behavior to ensure that

import module.submodule

now always works, no need to use import module.submodule as submodule

**Comment by amitu** [comment]
I can verify, I was wrong.
