### ISSUE TITLE
any plans of supporting jsx like tags?

### ISSUE THREAD

**Issue by amitu** [kovidgoyal/rapydscript-ng#23]
My experiment, vyom, works very well in moving all my main application logic to a python like language (rs), but I still am forced to use JSX/javascript for react components: https://github.com/amitu/vyom/blob/master/TodoMVC/components.jsx. 

It would be cool if rs-ng supported JSX like tags, tho I am not really sure how precisely it would work. Have you given it any thought?

**Comment by kovidgoyal** [comment]
Personally, I find JSX (and really all of react), a solution looking for a problem. What I use to build DOM trees in rs-ng is the elementmaker stdlib module, so for example, the render function in the HeaderView becomes:

```py
from elementmaker import E

return E.div(
   E.h1(todos),
   E.input(class_='new-todo', ref='inp', onkeypress=this.onKey, placeholder='...'
)
```

This module is documented in the readme under building dom trees.

**Comment by amitu** [comment]
Umm. I started from a position similar to yours, but after seeing the work done in React Native I tend to feel there is a bit of value there.

Ignore the ticket tho.

**Comment by kovidgoyal** [comment]
I dont see how I am ignoring this ticket, since I presented you with a way to build DOM trees in rs-ng that works just like JSX, except that it does not require the unnecessarily verbose XML based syntax .

**Comment by joystein** [comment]
@kovidgoyal i'm surprised that you emphasize DOM creation as the main problem that react tries to solve. My impression was that it is the virtual DOM and the diff algorithm that sets it apart.

(as an aside, i don't think @amitu meant to imply that you have willfully ignored this ticket, just that you should feel free to ignore it)

**Comment by kovidgoyal** [comment]
Quoting the OP
"It would be cool if rs-ng supported JSX like tags, tho I am not really sure how precisely it would work. Have you given it any thought?"

JSX is the only part of React that (as far as I know) that one cannot directly use in rs-ng -- so that is the part that I was addressing. 

As for virtual DOM -- in my experience it is useless, as long as you keep in mind a few basic principles of what causes redraws in the layout engine when designing your UI. In any case, there is nothing preventing the use of React in rs-ng, so if you find React useful, by all means feel free to use it.

**Comment by amitu** [comment]
Apologies for ambiguous wording, I did mean, please ignore this issue. :-p

I just realised I can always do:

```
    return v'''(
        <div className="chat-prompt">
            <input type="button" value={this.state.yes}
                   onClick={this.props.yes_clicked}/>
            <input type="button" value={this.state.no}
                   onClick={this.props.no_clicked}/>
        </div>
    )'''
```

Which produces:

```js
        return (
        <div className="chat-prompt">
            <input type="button" value={this.state.yes}
                   onClick={this.props.yes_clicked}/>
            <input type="button" value={this.state.no}
                   onClick={this.props.no_clicked}/>
        </div>
    );
```

This should work. 

One question: what is `this` in methods in rs-ng? Can I assume it will always be same as `self`?

**Comment by kovidgoyal** [comment]
This follows the same rules as in javascript. In a bound emthod it will be self. In unbound methods it will be whatever it would have been in strict mode javascript.

**Comment by amitu** [comment]
Can I assume self == this in all circumstances?

**Comment by kovidgoyal** [comment]
No you can assume that in a bound method this === the first argument which can be named anything, not just self.

**Comment by amitu** [comment]
Cool. Thanks.
