### ISSUE TITLE
how to find a module by name?

### ISSUE THREAD

**Issue by amitu** [kovidgoyal/rapydscript-ng#25]
In python I can do `import sys; sys.modules[name]`. I need to do this in rs-ng. I have currently hardcoded, `_$rapyd$_modules` from version 0.4.9, which is gone in 0.7.1, replaced by ρσ_modules.

https://github.com/amitu/vyom/blob/master/vyom/parser.pyj#L21-L34

What would be reliable way?

**Comment by kovidgoyal** [comment]
ρσ_modules is the current way. However, that is not guaranteed to be stable forever. I should probably write an importlib stdlib module someday that works like pythons.

**Comment by kovidgoyal** [comment]
On second thoughts, I dont think implementing importlib makes sense. Because in rs-ng importing is compile time, not runtime. Instead, I will create a builtin function get_module()

**Comment by amitu** [comment]
Thanks for such a fast turn around :-)
