### ISSUE TITLE
ES5 Embedded Compiler?

### ISSUE THREAD

**Issue by mardon86** [kovidgoyal/rapydscript-ng#28]
Hi @kovidgoyal I want to create an app using cordova + embedded rs-ng, but many of todays devices doesnt support ES6 natively yet. How to create embedded compiler that support ES5 ?
Thx

**Comment by kovidgoyal** [comment]
There is no easy way to do that. The problem is you have to embed very large libraries (regenerator and uglifyjs) to support ES 5 runtimes, which makes the embedded compiler size approx 6MB. Technically, I suppose one could create an ES 5 embedded compiler that does not support the yield statement (generators), in which case you dont need those libraries. If you want to do that, you can change js_version in embedded_compiler.js to 5 and run web-repl-export 

But note that the resulting compiler will error out if you use generators (yield statement) in your RapydScript.

**Comment by mardon86** [comment]
I tried to add {js_version:5} option argument to the compiler.compile function. But still doesnt work on my android browser (ICS).
Btw the rs-ng 0.4.7 works. Why the latest version doesnt ?
I tried also use the latest version [the way i use the version 0.4.7](https://github.com/mardon86/RapydScript-ng-0.4.7) but still doesnt work.
Thx.

**Comment by kovidgoyal** [comment]
It doesn't work with what error? I dont have mind reading powers.

**Comment by kovidgoyal** [comment]
And there has been no release with the above commit, so what do you mean by the latest version? To get the commit, you need to checkout rs-ng from source and then build the embedded compiler using bin/web-repl-export

**Comment by mardon86** [comment]
The android browser on my phone doesnt output any error message and doesnt have web console either.
I dont know how to get the commit, but this is from the rapydscript.js file:
```
var rs_version = "0.7.2";
var rs_commit_sha = "e888bbbe85e32677c4b6389309ff3d45abd7ca7c\n";
```

**Comment by mardon86** [comment]
This is the code i use:
```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<script src="rapydscript.js"></script>
		<script>
			var compiler = RapydScript.create_embedded_compiler();
			document.addEventListener("DOMContentLoaded", function() {
			    var pyscripts = document.getElementsByTagName("SCRIPT");
			    for (var i=0; i<pyscripts.length; i++) {
				    if(pyscripts[i].type == "text/python") {
					    eval(compiler.compile(pyscripts[i].text, {js_version: 5}));
				    }
			    }
			});
		</script>
		
<script type='text/python'>

def greet():
    alert("Hello")

greet()

</script>

	</head>
</html>
```
Works on firefox on android, but doesnt work on the androi native browser.
Thx.

**Comment by kovidgoyal** [comment]
Well I need an actual error message to be able to help.

**Comment by kovidgoyal** [comment]
I tested the embedded compiler on an ES 5 browser and it worked fine. One other thing that could be causing issues is the use of unicode symbols in rapydscript.js. Replace ρσ_ with _$rapyd$_ in rapydscript.js and see if it makes a difference.

**Comment by mardon86** [comment]
I tested at google chrome version 11.0.696.34 which have the same layout engine (and probably the javascript engine too) with my android browser (android 4.0.4). Resulting this error:
```
EvalError: The "this" object passed to eval must be the global object from which eval originated              rapydscript.js:194
Uncaught EvalError: The "this" object passed to eval must be the global object from which eval originated     rapydscript.js:196
  load                                                                                                        rapydscript.js:196
  vrequire                                                                                                    rapydscript.js:254
  create_embedded_compiler                                                                                    rapydscript.js:333
  (anonymous function)
```

**Comment by kovidgoyal** [comment]
That implies your android browser is an ES3 runtime, see this http://perfectionkills.com/global-eval-what-are-the-options/#eval_context_in_webkit

You might be able to get away with using an indirect eval as described on that page, simply pass it as an argument to create_embedded_compiler()

**Comment by mardon86** [comment]
Im not sure what to pass to the create_embedded_compiler(). I tried to pass `window.eval` as an argument. Still doest work. The eval things always make me confusing. 

Btw i tried to use the compiler.js baselib-plain-pretty.js file directly.
- Remove the outer IIFE
- Give global access to parse function and OutputStream function

Then the compiler give error message:
```
Uncaught TypeError: Cannot assign to read only property '__argnames__' of function Exception() {
    if (this.ρσ_object_id === undefined) Object.defineProperty(this, "ρσ_object_id", {"value":++ρσ_object_counter});
    Exception.prototype.__init__.apply(this, arguments);
}
```
I dont know why is `__argnames__` read only
so i tried to comment it out:
```
//Exception.__argnames__ = Exception.prototype.__init__.__argnames__;
```
and others too (that give the same kind of error message):
```
//DefaultsError.__argnames__ = DefaultsError.prototype.__init__.__argnames__;
//SyntaxError.__argnames__ = SyntaxError.prototype.__init__.__argnames__;
//OutputStream.__argnames__ = OutputStream.prototype.__init__.__argnames__;
```
And... it works!!

RapydScript is great! I think you should create an embeddable compiler support for ES3 runtime too.. so RapydScript will be 'everywhere'. web, node, pc, linux, mac, android, ios, cordova, nativescript, etc...
Thx

**Comment by kovidgoyal** [comment]
window.eval is not an indirect eval, you need to use something like:
```js
var globalEval = (function() {

  var isIndirectEvalGlobal = (function(original, Object) {
    try {
      // Does `Object` resolve to a local variable, or to a global, built-in `Object`,
      // reference to which we passed as a first argument?
      return (1,eval)('Object') === original;
    }
    catch(err) {
      // if indirect eval errors out (as allowed per ES3), then just bail out with `false`
      return false;
    }
  })(Object, 123);

  if (isIndirectEvalGlobal) {

    // if indirect eval executes code globally, use it
    return function(expression) {
      return (1,eval)(expression);
    };
  }
  else if (typeof window.execScript !== 'undefined') {

    // if `window.execScript exists`, use it
    return function(expression) {
      return window.execScript(expression);
    };
  }

  // otherwise, globalEval is `undefined` since nothing is returned
})();
```

and pass that to create_embedded_compiler.

As for readonly, that is a bug in the JS runtime you are using. 

Exception.__prototype__.__init__ is readonly (because is is created as readonly using Object.defineProperty) not Exception.__init__

It may be that this bug is triggered by removing the enclosing scope because the JS no longer runs in strict mode. In any case to workaround it, dont comment out the assignment, instead change 

```js
Object.defineProperties(Exception.prototype.__init__, {
    __argnames__ : {value: ["message"]}
});
```

to

```
Object.defineProperties(Exception.prototype.__init__, {
    __argnames__ : {value: ["message"], writable:true}
});
```

As for officially supporting ES3, I'm afraid that is not going to happen. There are too many corner cases to handle and it would mean, a lot of extra work and various features in rs-ng would have to have sub-optimal implementations, to work around ES 3 limitations.

**Comment by mardon86** [comment]
I tried using your code then passing the `globalEval` doesnt work

i tried this too:
```
indEval = (function(eval) {
    return function(s) {
      return eval(s)
    };
  })(eval);
```
then passing indEval. Doesnt work too with the same error message.

If officially supporting ES3 is not going to happen, at least officially supporting embedded ES5 is great!
thx.

**Comment by kovidgoyal** [comment]
Yes, embedded ES 5 is official supported (witht he caveat that you cannot use yield/generators)

**Comment by mardon86** [comment]
I tried again using rs-ng. I tried to alerting the exception when i using rs-ng for compiling on my android browser, finally i got the actual error message. (i dont know why this isnt in my head 7 months ago :D)

Here it is (on android) :

      ReferenceError: Symbol is not defined

(this works fine on mozilla and chrome)

**Comment by kovidgoyal** [comment]
That's odd as Symbol is only used in two lines in the compiler and there it is protected by typeof check to make sure it is defined. https://github.com/kovidgoyal/rapydscript-ng/blob/master/release/compiler.js#L3 

Is there a linenumber/stack trace associated with that error?

**Comment by mardon86** [comment]
This the only code i tested:
```
<!doctype html>
<html>
<head>
<meta charset='utf-8'>
<script src='rs-ng.js'></script>
</head>
<body>
<script>

var rscode='alert(\'hello\')';

try {
    var compiler = RapydScript.create_embedded_compiler();
    var js_out = compiler.compile(rscode);
} catch (err) {
    alert(err.name + ': ' + err.message);
}

eval(js_out);

</script>
</body>
</html>
```

![screenshot_2016-12-03-01-18-45](https://cloud.githubusercontent.com/assets/9649930/20845416/934e05f8-b8f7-11e6-8c36-199ae63b2527.jpg)

**Comment by kovidgoyal** [comment]
Put the try catch around each line individually and check if the err object has a stack attribute and alert that.

**Comment by kovidgoyal** [comment]
Oh and you have to use

compiler.compile(code, {js_version:5})

**Comment by mardon86** [comment]
The error comes from compiler creation

![screenshot_2016-12-03-12-07-52](https://cloud.githubusercontent.com/assets/9649930/20857025/92449806-b952-11e6-8da9-8275e4940790.jpg)

**Comment by kovidgoyal** [comment]
That's just weird there is nowhere that Symbol is used unprotected in that codepath, that I can see. You sure you are using the latest version of the embedded compiler? The line numbers in that stack trace dont match up (although that could be for other reasons). I just made a new release, try downloading that and see what happens. This commit might fix the problem (although I dont see why it would be needed) https://github.com/kovidgoyal/rapydscript-ng/commit/9fefd4728a0d255aaaa815cb458f9ede3285115c

**Comment by mardon86** [comment]
Im using the one from https://kovidgoyal.github.io/rapydscript/repl/rapydscript.js is it up to date ?

**Comment by kovidgoyal** [comment]
Yes it is, but download it again -- I just made a new release.

**Comment by mardon86** [comment]
It works but,, this error showed up before the code is working (alerting 'hello')
this error is coming from creating js_out (the compiling process ?)
![screenshot_2016-12-03-13-33-09](https://cloud.githubusercontent.com/assets/9649930/20857440/32acfd04-b95f-11e6-954e-5c5e9a65d0a4.jpg)

**Comment by mardon86** [comment]
Ups sorry there's no error showed up. Accidentally i typed 'c' in my code. So the rs-ng is working in my android browser now. thx @kovidgoyal

**Comment by mardon86** [comment]
i also tried to not using {js_version:5}, still working..

**Comment by kovidgoyal** [comment]
js_version:5 will only come into play if you use some feature in your code that has an ES 6 based implementation as well as an ES 5 based implementation.
