### ISSUE TITLE
Embedded RapydScript test fails

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#29]
```
When I try the test of embedded RapydScript shown below, I get errors in both Firefox and Chrome.

Firefox:
Error: Unexpected token punc <<:>>, expected punc <<(>>          <embedded>:1:0
KL.CB   DocumentNotifier.onLoadDocument exc: Unknown window      tracer.js:22:0

Chrome:
Uncaught ReferenceError: ρσ_bool is not defined      VM575:9,  Object.defineProperties(ρσ_bool, {

-------------------------------
I added the statement "<meta charset="UTF-8">" to prevent other errors that occurred:

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"> 
        <title>Test embedded RapydScript</title>
        <script src="https://kovidgoyal.github.io/rapydscript/repl/rapydscript.js"></script>
        <script>
var compiler = RapydScript.create_embedded_compiler()
var js = compiler.compile("def hellow_world:\n a='RapydScript is cool!'\n print(a)\n alert(a)")
window.onload = function() {
    document.body.textContent = js
    eval(js)
    eval('hello_world()')
}
        </script>
    </head>
    <body style="white-space:pre-wrap"></body>
</html>
```

**Comment by kovidgoyal** [comment]
You have a typo in your code, see where you have 
def hellow_world:

instead of

def hello_world():

**Comment by BruceSherwood** [comment]
Thanks for catching the typo, but the problem seems to occur earlier in the process, and fixing the mistake doesn't change the errors I see. I think I got this test routine from you (but possibly miscopied, evidently); does it work for you? Or do you have a different test routine I should try?

**Comment by kovidgoyal** [comment]
Works fine fro me in Firefox -- I haven't tested it in other browsers.

On Tue, May 17, 2016 at 08:03:27PM -0700, BruceSherwood wrote:
> Thanks for catching the typo, but the problem seems to occur earlier in the process, and fixing the mistake doesn't change the errors I see. I think I got this test routine from you (but possibly miscopied, evidently); does it work for you? Or do you have a different test routine I should try?
> 
> ---
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/rapydscript-ng/issues/29#issuecomment-219913254

-- 
_____________________________________

Dr. Kovid Goyal 
http://www.kovidgoyal.net
http://calibre-ebook.com
_____________________________________

**Comment by BruceSherwood** [comment]
Works for me in Firefox and Edge, but not in Chrome (this is Windows 10). Surprising. The Chrome error is (still) 

`Uncaught ReferenceError: ρσ_bool is not defined`

Character encoding issue?

**Comment by kovidgoyal** [comment]
No, it will be because eval() on Chrome works differently/is broken compared to the
other browsers. Fixing it will take some investigation -- basically, that error is coming from
eval(JS)

where JS = the contents of baselib-plain-pretty.js 

I have no idea why chrome barfs on that.

On Tue, May 17, 2016 at 09:02:21PM -0700, BruceSherwood wrote:
> Works for me in Firefox and Edge, but not in Chrome (this is Windows 10). Surprising. The Chrome error is (still) 
> 
> `Uncaught ReferenceError: ρσ_bool is not defined`
> 
> Character encoding issue?
> 
> ---
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/rapydscript-ng/issues/29#issuecomment-219919713

-- 
_____________________________________

Dr. Kovid Goyal 
http://www.kovidgoyal.net
http://calibre-ebook.com
_____________________________________

**Comment by kovidgoyal** [comment]
It was indeed a bug in Chrome -- I have committed a workaround. Incidentally the example for using the embedded compiler is in the readme.

**Comment by BruceSherwood** [comment]
Kovid, you are amazingly responsive. Thank you!
