### ISSUE TITLE
Building a library

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#30]
In the README is a discussion about issues in calling routines in external libraries. I need to go the other way, to produce from Python code a JavaScript library. I successfully executed "npm install rapydscript-ng" and "npm install" and successfully ran "rapydscript" which produced what looks like correct JavaScript output, but when I try to reference a function named "PhysGraph" in the library (which is a class in the original Python file) I get an error message "PhysGraph is not defined", despite the fact that there is a "function PhysGraph" in the JavaScript. Do you have any suggestions about what I've done wrong? Thanks. (Incidentally, when I initially ran the Python code through the REPL, the output was entirely different and, in particular, didn't include any of the RS run-time functions. I guess the REPL is just used for seeing how code fragments compile?)

**Comment by amitu** [comment]
Try --bare flag.

**Comment by BruceSherwood** [comment]
Thanks, I'll try that. Where does one find documentation on flags such as "bare"?

**Comment by amitu** [comment]
--help on command line. Sub commands like compile have their own help too.

**Comment by kovidgoyal** [comment]
By default all output produced by the compiler is in a private scope. You can use --bare or simply export the symbol manually by doing something like (I would recommend the latter approach since otherwise you pollute the global namespace with lots of unneeded things).

window.PhysGraph = PhysGraph in the .pyj file.
