### ISSUE TITLE
Class variable?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#31]
Thanks to being told about "--bare", I'm close to building a library, but in my Python program I have a class variable (a list) which is omitted from the resulting JS. I see in the README how to make a class method (@staticmethod), but I don't see how to make a class variable.

**Comment by kovidgoyal** [comment]
Works for me:

```py
class A:
   X = [1, 2]
print(A.X) // prints [1,2]
a = A()
print(a.X) // prints [1,2]
```

**Comment by BruceSherwood** [comment]
And now for me, too. Dunno what I did. Sorry.
