### ISSUE TITLE
Class returning as undefined

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#32]
I prepared this simple test file in ClassA.py:

```
from __python__ import bound_methods
class A:
    def __init__(self,x):
        self.x = x
    def get(self):
        return self.x
b = A(5)
console.log(b)
c = b.get()
console.log(c)
```

I transpiled it with "rapydscript --bare --output ClassA.js ClassA.py"

I tested it as a library with this code:

```
test = A(23)
console.log(test)
t = test.get()
```

The output was 

```
A {x: 5, ?s_object_id: 1}
5
undefined
```

followed by the error message TypeError: Cannot read property 'get' of undefined.

What am I doing wrong?

**Comment by kovidgoyal** [comment]
You forgot new

**Comment by BruceSherwood** [comment]
Duh. And I confused what's possible within a self-contained program and in an external library. As your README says about new, "This is very useful for avoiding a common JavaScript error of creating 'undefined' objects by forgetting this keyword."

MIght it be useful to have a compile flag, say "--library", so that a Python class would be compiled to something like this?

```
function PhysAxis(obj, numLabels, args) {
    if (!(this instanceof PhysAxis)) return new PhysAxis(obj, numLabels, args)
```

**Comment by kovidgoyal** [comment]
Not worth it, IMO. Every extra output option, slows down compilation, because the result of running with it has to be cached, to enable incremental compilation. Also, it means that the function cannot be used as a generic anymore, which is common in at least some parts of the JS ecosystem, and I think it will break at least some types of multiple inheritance.

**Comment by BruceSherwood** [comment]
I obviously don't know all the ramifications, but if it were an optional flag?
