### ISSUE TITLE
Possibilities of integration into JS Frameworks?

### ISSUE THREAD

**Issue by v3ss0n** [kovidgoyal/rapydscript-ng#34]
Do you think we can integrate rapydscript into JS Framework like Emberjs ?
That way we can forget about javascript.

**Comment by kovidgoyal** [comment]
I'm not sure what you are asking here? You can use rapydscript with any javascript library/framework you like. Just like you call DOM functions in RapydScript, you can call functions from other libraries.

**Comment by v3ss0n** [comment]
it use a cli-framework so i am not sure how it will adapt to it . thinking to try.

**Comment by kovidgoyal** [comment]
I'm afraid I dont know anything about ember, but if you have RS related questions, I will try to help.
