### ISSUE TITLE
Bug using map() with functions with default keyword arguments?

### ISSUE THREAD

**Issue by araichev** [kovidgoyal/rapydscript-ng#35]
Hi there,

I'm using RapydScript 0.7.3 and  just discovered that my functions with default keyword arguments don't work with JavaScript's map() function.
Here's a code snippet to illustrate the problem. 

------------------------------------------------------------------

    Welcome to the RapydScript REPL! Press Ctrl+C then Ctrl+D to quit.
    Use show_js=False to stop the REPL from showing the compiled JavaScript.

    >>> def f(x):
    ...     return str(x)
    ...     
    ...     
    ---------- Compiled JavaScript ---------
    function f(x) {
        return str(x);
    };
    Object.defineProperties(f, {
        __argnames__ : {value: ["x"]}
    });

    ---------- Running JavaScript ---------
    [Function: f]
    >>> def g(x, flag=True):
    ...     if flag:
    ...         x = str(x)
    ...     return x
    ...     
    ...     
    ---------- Compiled JavaScript ---------
    function g() {
        var x = ( 0 === arguments.length-1 && arguments[arguments.length-1] !== null && typeof arguments[arguments.length-1] === "object" && arguments[arguments.length-1] [ρσ_kwargs_symbol] === true) ? undefined : arguments[0];
        var flag = (arguments[1] === undefined || ( 1 === arguments.length-1 && arguments[arguments.length-1] !== null && typeof arguments[arguments.length-1] === "object" && arguments[arguments.length-1] [ρσ_kwargs_symbol] === true)) ? g.__defaults__.flag : arguments[1];
        var ρσ_kwargs_obj = arguments[arguments.length-1];
        if (ρσ_kwargs_obj === null || typeof ρσ_kwargs_obj !== "object" || ρσ_kwargs_obj [ρσ_kwargs_symbol] !== true) ρσ_kwargs_obj = {};
        if (Object.prototype.hasOwnProperty.call(ρσ_kwargs_obj, "flag")){
            flag = ρσ_kwargs_obj.flag;
        }
        if (flag) {
            x = str(x);
        }
        return x;
    };
    Object.defineProperties(g, {
        __defaults__ : {value: {flag:true}},
        __handles_kwarg_interpolation__ : {value: true},
        __argnames__ : {value: ["x", "flag"]}
    });

    ---------- Running JavaScript ---------
    [Function: g]
    >>> a = [1, 2]
    ---------- Compiled JavaScript ---------
    var a;
    a = ρσ_list_decorate([ 1, 2 ]);
    ---------- Running JavaScript ---------
    [1, 2]
    >>> a.map(f)
    ---------- Compiled JavaScript ---------
    a.map(f);
    ---------- Running JavaScript ---------
    [ '1', '2' ]
    >>> a.map(g)  # Should be the same as a.map(f)
    ---------- Compiled JavaScript ---------
    a.map(g);
    ---------- Running JavaScript ---------
    [ 1, '2' ]

**Comment by kovidgoyal** [comment]
You cannot use starargs, kwargs, default keywords with javascript, only with RapydScript. If you are designing functions for use with javascript use only plain arguments, or use the @options_object decorator, as described in the README. 

And note that RapydScript has its own map() function that behaves just like pythons. So you can do

list(map(f, [1,2]))

**Comment by kovidgoyal** [comment]
Finally, if you want to use a function with the JS map() the function needs to have the signature:

```py
def f(x, index, array, flag=True):
   pass
```

This is because the JS map() calls functions with three arguments not one argument.
