### ISSUE TITLE
Starting issues

### ISSUE THREAD

**Issue by drebutler** [kovidgoyal/rapydscript-ng#36]
This may not be a real issue, or maybe at most a documentation issue, but I what I get attempting to compile my own code on my machine (Debian Linux) does not match the examples in the documentation nor what the REPL on this site gives me and (more importantly) doesn't work.  It appears that what I get includes an enormous library of additional material and that somewhere in there something is causing a problem.  When I strip this out the code works.

I don't know if this is a problem within the standard library or a user error in which I am compiling something wrong.  I am currently compiling my code by issuing the command "rapydscript <file> -o <output file>" in a terminal.  I do notice that several of the symbols in the library code do not get displayed correctly when I view the source in the browser but I doubt that this is enough to break the code.

**Comment by kovidgoyal** [comment]
The output of the RapydScript compiler includes a base library that rapydscript code needs. If you dont want to include the base library in the compiler output use the option --omit-baselib

However, most rapydscript code will not work without including the baselib. As for symbols not displaying correctly, if your system default charset is not utf-8 then you will need to declare the utf-8 character encoding in the <script> tag you use to include the generated javascript.

`<script charset="UTF-8" src="output.js">`
