### ISSUE TITLE
abs, min, max

### ISSUE THREAD

**Issue by mardon86** [kovidgoyal/rapydscript-ng#4]
Hi @kovidgoyal I looked into baselib.pyj, and found these functions:
```
def abs():
    return Math.abs
def max():
    return Math.max
def min():
    return Math.min
```

I think they should be something like:
```
def abs(x):
    return Math.abs(x)
def max(x):
    return Math.max(x)
def min(x):
    return Math.min(x)
```

CMIIW. What do you think ?

**Comment by kovidgoyal** [comment]
No, they are correct, it is a performance optimization to avoid an extra function call. They way it works is that in the output javascript you get (something like)

```js
var abs = (function () { return Math.abs; })()
```
