### ISSUE TITLE
A typo, and a question about separating browser compiler and run-time

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#41]
Minor typo: In the reference to the work of Brian Turek, http://caligatio.github.com/jsSHA/ should be http://caligatio.github.io/jsSHA/

Kovid, I'm in the process of converting glowscript.org from rapydscript to rapydscript-ng. I had a useful exchange with Alex in which he and I agreed that my needs align better with your goals than with his. He wants to build an optimal tool for web programmers, with an appropriate mix of Python and JavaScript. I perceive that your goals are more along the lines of approximating true Python, without major sacrifices in run-time speed. The importance for VPython is that Ruth Chabay and I have been working hard to make the syntax of GlowScript VPython and Jupyter VPython be exactly the same, and it is the case that as long as outside libraries are not needed the same VPython program will run in both, very different, environments. Moreover, much of the use of VPython is in academic settings where Classic Python is used, both in STEM courses and in scientific work, so the closer the approximation the better.

My question: It's very helpful that you provide a ready-to-use in-browser compiler. I would like to separate the in-browser compiler from the run-time libraries, so that once the user program has been compiled it needs a smaller library in order to run. Can you explain what I need to do to create these two files?

The number of users registered at glowscript.org continues to rise dramatically, thanks to RapydScript:

http://www.glowscript.org/#/user/Bruce_Sherwood/folder/My_Programs/program/Users

**Comment by kovidgoyal** [comment]
I'm not sure I understand your question. You want the user to compile their rapydscript program in a browser and then use it elsewhere? The baselib can be generated from any rapydscript compiler by simply compiling a trivial rapydscript program like say

1

with the --bare option and then deleting the last couple of lines from the output.

**Comment by BruceSherwood** [comment]
At glowscript.org the user writes a program, clicks "Run", and the program
is compiled in the browser and then run in the browser. However, when
editing the program, the user can click "Share this program" in which case
the compiler generates html+JS code that the user can copy and insert into
their own web page. This package includes a reference to a run-time library
served from glowscript.org. It's advantageous in this situation that the
run-time library be small, and not include the extensive code used for
compilation.

So my question is how to generate the run-time library, which you have
apparently answered. I'll try it. Thanks.
