### ISSUE TITLE
dict function?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#42]
The dict function, as in dict(a=5, b=3), gives an error when using the in-browser compiler. Am I failing to invoke some RS library?

**Comment by kovidgoyal** [comment]
Works for me, what error are you getting? Note that currently the dict function does not support keyword arguments, it will simply ignore them and create an empty dict.

**Comment by kovidgoyal** [comment]
And this commit takes care of the keyword args being ignored: https://github.com/kovidgoyal/rapydscript-ng/commit/438be8b5163b54b7ad0215972851c0ca0cde4d1c

**Comment by BruceSherwood** [comment]
Correction: it doesn't give an error (its use in a function gave an error), rather the elements are undefined:
d = dict(a=5, b=3)
console.log(d.a, d.b) # undefined, undefined

**Comment by kovidgoyal** [comment]
See my previous comments. And note that the dict() function does not create javascript dicts, so you cannot access the members using attribute notation. Use d['a'] just as you would in python, after setting the appropriate scoped flag. See the section on dicts in the readme.

**Comment by BruceSherwood** [comment]
Yeah, it was dumb of me to try d.a. But more importantly I had forgotten the README info. Thanks.
