### ISSUE TITLE
Success! And a question

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#43]
Thanks to your help (and work) I've been able to use rapydscript-ng in a test version of glowscript.org, even without updating the acorn and streamline libraries that permit operator overloading and synchronous code.  I had to replace all instances of ρσ with RS because the streamline library considered ρσ to be an error, and perhaps updating streamline will eliminate that problem.

I think it is the case that I'm using acorn and streamline libraries that expect ES5, and I thought you said that you generate ES6, so I'm puzzled that this all works. I'm not knowledgeable in ES6, but looking at your generated code I don't see non-ES5 elements. Maybe I'm accidentally using Python code that doesn't happen to invoke ES6. Can you give an example of Python code that generates ES6? Thanks.

**Comment by kovidgoyal** [comment]
rs-ng can generate either ES5 or ES6 depending on a compiler parameter. See the note on how to generate ES5 with the web compiler here: https://github.com/kovidgoyal/rapydscript-ng#embedding-the-rapydscript-compiler-in-your-webpage
