### ISSUE TITLE
Checking if stuff from original was/is pulled into this fork

### ISSUE THREAD

**Issue by hir3npatel** [kovidgoyal/rapydscript-ng#45]
Hi, the original repo seems to have had some commits over Oct/Nov, which mostly looked like fixes. I was just wondering if most of these are in this repo already, or if they are planned to be pulled in. Thanks!

**Comment by kovidgoyal** [comment]
The code bases have diverged a lot. I try to keep an eye on the commits in the original repo and apply any that are still relevant, but lots of the fixes there are not needed here. Many of those bugs were squashed in rs-ng a long time ago. 

Of course, I could have missed some things -- so pull requests are welcome.
