### ISSUE TITLE
Speed comparisons

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#46]
Kovid, you might find interesting this speed comparison with Brython that I posted on the Brython forum:

https://groups.google.com/forum/?fromgroups&hl=en#!topic/brython/20hAC9L3ayE

**Comment by kovidgoyal** [comment]
Thanks. It is pretty much what I would expect. Full python is really slow, so trying to emulate it fully in JS will be even slower. The nice thing about rs-ng is that (IMO) it hits a sweet spot where the behavior/syntax is sufficiently pythonic for many/most? use cases, but the performance is still close to that of native JS, which in turn is not too far from native code when run on modern JITed JS engines.

And the icing on the cake is that in rs-ng, thanks to scoped flags, one can tune the language along the python emulation -- perfomance axis to whatever is appropriate for the particular use case.
