### ISSUE TITLE
Technical ebook user interface

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#47]
I agree that "sweet spot" is an excellent description of rs-ng.

I clicked on your photo and was led to your brief bio, where I was reminded that you have a Ph.D. in physics from Caltech. My first position as a physicist was at Caltech in 1966-1969, where I was in a group doing experimental particle physics at SLAC and the Berkeley Bevatron, with lots of computer involvement, and teaching intro physics using as textbook the Feyman Lectures on Physics, which was a fabulous experience and which led to leaving particle physics for physics education, including the use of computers. The textbook "Matter & Interactions" that Ruth Chabay and I have written was strongly influenced by the Feynman textbook. 

Like you, I read a lot (in multiple languages), and for many years almost all my book reading has been of ebooks, especially Kindle books, not only on Kindle readers. Your physics and ebook experience suggest that you might be interested in addressing what I see as a serious problem with ebooks on technical matters, including textbooks. It is something that someone ought to be willing pay a significant amount for a solution. The issue is that ebooks work fine for many kinds of books that are read pretty much linearly, such as novels and biographies and histories, but the current user interface is pretty bad for studying technical books, where one continually flips forward and back.

At the start of the GlowScript project five years ago I had lots of programming experience but knew nothing about web programming. I made the deliberate choice to read books on web programming in ebook form, to experience something of the reactions students might have to electronic textbooks. What I found was that it is difficult to flip forward and back, looking for something like "the page that had a predominantly red figure at the upper right" and to return easily to the original page. Yes, the ebook has a search capability, but it's not a Google-like search, it's a search for a specific character string, which is often nearly useless. The closest approach I've seen so far to a good interface is the one on current Kindle devices, where moving back and forth with easy return to the original page is sort of okay but not great. In a long book with a scroll bar, it would be better for the slider to embody acceleration, to make it easy to make small moves, rather than a small motion jumping several pages. Etc.

The point is, it looks like no one has thought seriously about what the user interface ought to look like for technical books. I'm guessing it could be much better than paper books, but that's not the current situation. There's a special concern about textbooks, because there seems to be a lot of student resistance to etextbooks despite their far lower price, due I would guess to the awkwardness to studying an etextbook.

You of all people have the skill set needed to make a far better user interface for technical use. Have you already thought about this?

I'll mention that Ruth and I would love to include GlowScript VPython 3D animations in the next (5th) edition of our textbooks, which is another reason why we're interested in etextbooks being attractive to students. A colleague has already done some little experiments with this.

Bruce
bruce.sherwood@gmail.com

**Comment by kovidgoyal** [comment]
Generally speaking, the answer to that is to have a dedicated page quick flip control -- essentially a scrollbar with a button to abort/return to page before scroll. It's not particlarly hard to implement. You can simulate it in the calibre ebook viewer by using the existing scrollbary + bookmark functionality. However, this is something that has to be solved on each individual reading platform, not something that can be done during creation of ebooks.
