### ISSUE TITLE
global and nonlocal

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#48]
The documentation advocates the use of nonlocal rather than global, with reference to Python 3, with the comment "There is also global". However, it looks like a bug that RS 1) has not implemented "global" and 2) has not restricted "nonlocal" to use in nested methods, as seems to be the case in Python 3. At the time of implementing the use of RS in GlowScript, I was unfamiliar with "nonlocal" and in a preprocessing stage simply converted a user program "global" to "nonlocal", which did what was expected, except that in true Python one need not separately declare the variable in global scope, whereas in RS one must do so. Am I confused, or is this a bug?

**Comment by kovidgoyal** [comment]
1) is a documentation bug, now fixed.

2) Not sure what you mean. If you dont delare a nonlocal variable in the outer scope in python, what value would it take in the inner scope? For example, running the following python3 script, gives a SyntaxError

```python
def f():
    nonlocal a
    print(a)
```

SyntaxError: no binding for nonlocal 'a' found

rs-ng generates for the same snippet
```js
 function f() {                                                                                                                                                                                  
            print(a);
        };  
```

which will print nothing since a is undefined.

**Comment by BruceSherwood** [comment]
I'm puzzled, Kovid. When I run your own README example in Python 3, 

a = 1
b = 1
def increment():
    nonlocal a
    a += b
increment()
print(a)

I get the error "SyntaxError: no binding for nonlocal 'a' found". I have to change nonlocal to global to get the expected result of a = 2. Shouldn't RapydScript support both the standard Python global and nonlocal options, rather than redefine the meaning of nonlocal? What am I missing?

**Comment by kovidgoyal** [comment]
Ah I get your confusion -- python has this crazy system where variables in the "global" i.e. module scope are special and need to use global keyword while variables in an outer scope, but **not** the global scope need the nonlocal keyword. RS simplifies this unnecessarily baroque system to just have nonlocal which works with any scope regardless of whether it is the global or only outer scope. So the only incompatibility between python and rs is when you have a global variable that is used in an iner scope but is also sahdowed in an outer scope. In python, you can ignore the outer scopes and go direct to the module scope  by using global instead of nonlocal in RS it will always use the variable from the next outer scope, there is no way to bypass all scopes and go to module scope.

**Comment by BruceSherwood** [comment]
Thanks much for this explanation, which should (in some form) be added to the README documentation. You have a good logical argument for extending nonlocal. However, in the GlowScript case it's also important to support global, which I think I can do in the fairly extensive preprocessing I do before sending the code to rapydscript. 

The reasons for needing to support global is that we try hard to make the same program work whether it runs in GlowScript VPython (all browser with RS) or in Jupyter VPython (Jupyter notebook with true Python), limited of course to not using a module such as numpy, and global is a commonly used Python element. Moreover, the following should work, and print "5", whereas with nonlocal, "a" must be initialized outside the function, which is mildly inconvenient:

```
def f():
    global a
    a = 5
f()
print(a)
```

What I can do is detect "global a", change this to "nonlocal a", and insert at the start of the program "a = None". It would be better though if RS supported global, while continuing to support the extended version of nonlocal. Currently I do change global -> nonlocal before the RS transpiling, but I should also set the variables to None at the start of the program. You've helped me see what I need to do.

**Comment by kovidgoyal** [comment]
Also, using global without declaring the variable in the global namespace is a pretty bad code pattern, for instance, in python3, the following code will raise a SyntaxError

```py
def f():
   global a
   a = 1
print(a)
```

If you dont declare the variable in the global scope, you have to ensure some function that uses it is called *before* the referenced variable is used anywhere -- which is very fragile for obvious reasons.

**Comment by BruceSherwood** [comment]
Wow! You are remarkable, Kovid. Your dedication to your users is amazing, as is the speed of your response. Thank you for global.

I of course am using the embedded version of the transpiler; has that been updated to support global? How would I know whether/when the embedded version is up-to-date with the rapydscript-ng repository?

As for "patches are welcome", I would love to contribute to RS. It has made a huge difference in my professional life, because it made it possible for programming novices, including in particular the many students who use the physics textbook that Ruth Chabay and I wrote, to do their work at glowscript.org without having to install anything, which greatly increased their enthusiasm for using VPython. At the moment I can't contribute directly due to many pressures that include a major cross-country move Ruth and I made a few weeks ago. I am however trying to make RS in general and RS-NG in particular much better known.

I was unaware of the behavior in Python of 

def f():
   global a
   a = 1
print(a)

**Comment by kovidgoyal** [comment]
I just realized there was an easy way to implement partial global support (basically it works just like nonlocal except it also declares the variables at the top level of the module -- see the changes to README for the caveat).

The embedded compiler is auto-updated every time a new rs-ng release is made. You can always generate your own from a source checkout, instructions are in the README.
