### ISSUE TITLE
String methods

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#49]
I'm excited to be able to invoke Python string and dict methods. I notice that there are quite a few string methods not yet implemented, and this is something I could perhaps contribute to if it's not on your own to-do list. I noticed one bug: in my tests both islower and isupper give true for either 'a' or 'A'.

**Comment by kovidgoyal** [comment]
What string methods are missing? IIRC I implemented more or less all of them. But you are welcome to contribute any you find missing, see the baselib-str.pyj file for implementing them.

**Comment by BruceSherwood** [comment]
Here is what I see in the generated code:

string_funcs = set("capitalize strip lstrip rstrip islower isupper isspace lower upper swapcase center count endswith startswith find rfind index rindex format join ljust rjust partition rpartition replace split rsplit splitlines zfill".split(" "));

The following Python 3 string methods are missing: isalnum, isalpha, isdecimal, isdigit, inumeric, istitle, title. There are a few others mentioned in Python 3 documentation that sound pretty technical, such as translate; not sure they are relevant.

**Comment by kovidgoyal** [comment]
Ah, yes feel free to contribute those if you want them -- I never use any of those methods myself.
