### ISSUE TITLE
named arguments

### ISSUE THREAD

**Issue by mardon86** [kovidgoyal/rapydscript-ng#5]
Calling a function with named argument is not working. It's working on the original rapydscript.

Welcome to the RapydScript REPL! Press Ctrl+C then Ctrl+D to quit.
Use show_js=False to stop the REPL from showing the compiled JavaScript.

>>> def test(a,b,c):
...     print('a=' + a + ', b=' + b + ', c=' + c)
...     
...     
---------- Compiled JavaScript ---------
function test(a, b, c) {
    print("a=" + a + ", b=" + b + ", c=" + c);
}
---------- Running JavaScript ---------
>>> test(1,2,3)
---------- Compiled JavaScript ---------
test(1, 2, 3);
---------- Running JavaScript ---------
a=1, b=2, c=3
>>> test(a=1,b=2,c=3)
---------- Compiled JavaScript ---------
test(_$rapyd$_desugar_kwargs({a: 1, b: 2, c: 3}));
---------- Running JavaScript ---------
a=[object Object], b=undefined, c=undefined

**Comment by mardon86** [comment]
rapydscript-ng 0.4.7
nodejs v5.1.0

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/rapydscript-ng#function-calling-with-optional-arguments in particular the last difference.
