### ISSUE TITLE
Duplication in in-browser compiler

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#50]
By accident I discovered that the minimized runtime code in the in-browser compiler (https://kovidgoyal.github.io/rapydscript/repl/rapydscript.js) has a large duplication. Code starting at 

var RS_len;\nfunction RS_bool(val) 

is duplicated after 

baselib-plain-pretty.js":".

I of course don't know whether this is deliberate; it just seemed strange. I don't find this duplication if I build a runtime file (which I guess isn't needed, since it's all apparently present in the in-browser compiler).

**Comment by kovidgoyal** [comment]
It is deliberate. The compiler has to be able to output the baselib when compiling, which means it needs the baselib stored in both minified and non-minified form in a dict so it can access it.

**Comment by kovidgoyal** [comment]
To be clear, there are three copies of the baselib in the compiler:

1) An active one that is used to run the compiler itself
2) A non-minified one stored as a string
3) A minified one stored as a string

The latter two are output by the compiler when compiling code depending on what compilation options are set.
