### ISSUE TITLE
Updated GlowScript to RS-NG

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#51]
I made the following announcement to the GlowScript user forum. Thanks very much, Kovid, for the software itself and for the help you gave me in moving from RS to RS-NG.

The new GlowScript version 2.3 is a major update. It replaces the original RapydScript Python-to-JavaScript compiler with a newer version, RapydScript-NG by Kovid Goyal. This new version comes closer to handling true Python syntax but continues to offer high execution speed. It also provides most of the standard Python string methods: capitalize, strip, lstrip, rstrip, islower, isupper, isspace, lower, upper, swapcase, center, count, endswith, startswith, find, rfind, index, rindex, format, join, ljust, rjust, partition, rpartition, replace, split, rsplit, splitlines, and zfill.

**Comment by kovidgoyal** [comment]
Glad to hear it, and you're welcome :)
