### ISSUE TITLE
range issue?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#52]
The inner loops here are not executed, as the output just shows x 0, x 1, x2:

```
xx = range(3)
for x in xx:
    console.log('x',x)
    for y in xx:
        console.log('   y',y)
        for z in xx:
            console.log('      z',z)
```

Evidently the problem is that xx is an iterator, not a list.  Both CPython and rapydscript do execute the inner loops. Is this a bug or a feature? It's the first bug report I've gotten since upgrading GlowScript to RS-NG.

**Comment by kovidgoyal** [comment]
Well the problem is that in python3 range() does not actually give a standard iterator, but a special object that apparently restarts after reaching the end, and has some special methods, like count() and index(). I suppose one could implement this in rs-ng as well.

**Comment by BruceSherwood** [comment]
I believe that originally in CPython range(N) actually produced a list of length N. This has obvious disadvantages, but it would be a simple implementation while considering a more elegant solution (maybe this is what RS does, since it works there). In any case, this does seem a rather significant departure from CPython, and an unexpected one, so it would be great if you see a way to implement it.

**Comment by kovidgoyal** [comment]
Sure, I'm not saying it should not be fixed. It will just be a little while before I can get to it. In the meantime, you can always change the implementation of range in baselib-builtins.pyj for yourself to use an array.

**Comment by BruceSherwood** [comment]
I tried the obvious changes, namely to replace the RS_range function in the run-time package and in the in-browser compiler, to construct a list, but then compiling doesn't work at all. I see that the range function is used for various purposes in the in-browser compiler, so maybe that's why I can't make the change?

**Comment by kovidgoyal** [comment]
I've already fixed this.

**Comment by BruceSherwood** [comment]
That's terrific (you're incredibly responsive!), but how do I recreate the in-browser compiler, which is still 0.7.11? The only way I know to get a new in-browser compiler is to go to 

https://kovidgoyal.github.io/rapydscript/repl/rapydscript.js

**Comment by kovidgoyal** [comment]
How to build the embedded compiler is documented in the readme

**Comment by BruceSherwood** [comment]
I really appreciate the documentation you provide on installing etc. Many repositories provide little such information. 

I had been using "npm install rapydscript-ng" followed by executing "rapydscript --bare input.py > runtime.js", where input.py just contains "a = 1", then deleting the last few lines, as you had explsined, and I obtained the mebedded compiler from kovidgoyal.github.io/rapydscript/repl/rapydscript.js. However, following that procedure didn't get me the changes to range(), so I built from source (on my Mac; bin/web-repl-export fails on my primary machine, a Windows 10 desktop). I'm curious:

1) What triggers an update to kovidgoyal.github.io/rapydscript/repl/rapydscript.js?

2) Under what circumstances will "npm install rapydscript-ng" not pick up the latest state of the repository?

**Comment by BruceSherwood** [comment]
Thanks.

When I built yesterday from source, I assumed that dev/baselib-plain-pretty.js would be the runtime file I needed (previously I ran rapydscript on "a=1" as you had explained to me). What I found was that the following preamble was missing from the start of dev/baselib-plain-pretty.js:

	var ρσ_iterator_symbol = (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") ? Symbol.iterator : "iterator-Symbol-5d0927e5554349048cf0e3762a228256";
	var ρσ_kwargs_symbol = (typeof Symbol === "function") ? Symbol("kwargs-object") : "kwargs-object-Symbol-5d0927e5554349048cf0e3762a228256";
	var ρσ_cond_temp, ρσ_expr_temp, ρσ_last_exception;
	var ρσ_object_counter = 0;
	var ρσ_len;

Is there some other file obtainable when working with the source that includes these essential definitions? Or should I have again run rapydscript on "a=1"?

**Comment by kovidgoyal** [comment]
To generate rapydscript.js just do:

```
./build
./bin/web-repl-export out
```

File is `out/rapydscript.js`

In any case I have updated the online one manually, so you can just use that.

**Comment by BruceSherwood** [comment]
I did run web-repl-export and picked up embedded_compiler/rapydscript.js. That's not the issue; the issue was how to construct the runtime library. I made the guess that it would be dev/baselib-plain-pretty.js, but in fact that file doesn't define ρσ_iterator_symbol, etc. Those five lines are the only pieces missing from using dev/baselib-plain-pretty.js as the runtime library.

**Comment by kovidgoyal** [comment]
Oh sorry (I've been rather swamped because I just released a new project to the public https://github.com/kovidgoyal/kitty so I did not pay as much attention as I should have) -- yeah you need to do the run trick again.

**Comment by BruceSherwood** [comment]
I found that I didn't understand how to "do the run trick" when working with the source. If I execute "rapydscript --bare input.py > runtime.js" I don't get the most recent changes. Presumably I need to use not "rapydscript" but dev/compiler.js, but I couldn't figure out in the node environment what command to issue.

**Comment by kovidgoyal** [comment]
First uninstall any previous rapydscript you have installed with npm. Then run

```
git clone git://github.com/kovidgoyal/rapydscript-ng.git
cd rapydscript-ng
sudo npm link .  # this will link the rapydscript executable to the current dir
npm install  # This will automatically install the dependencies for RapydScript
```

**Comment by BruceSherwood** [comment]
I'll try again, but I've always installed rapydscript locally, in its own initially empty directory. After executing the four statements you quote, my experience was that "rapydscript --bare input.py > runtime.js" didn't get the most recent changes, which is why I thought I had to invoke rapydscript a different way, maybe invoking the compiler in dev.
