### ISSUE TITLE
cant run on OSX

### ISSUE THREAD

**Issue by pepsiquantum** [kovidgoyal/rapydscript-ng#56]
Installed Versions
nodejs: v6.9.1
npm: 3.10.8
rapydscript@0.5.55

when I try to run rapydscript from the command line, I get the following error.

-bash: rapydscript: command not found

any help would be appreciated

**Comment by kovidgoyal** [comment]
That's not an installation od rapydscript-ng you need to ask for help in the rapydscript issue tracker. Although from that error, I'm guessing whatever path npm in installing binaries too on your system is not in your PATH variable. Fix that and you will be fine.
