### ISSUE TITLE
How to add source files to import_path at compilation time?

### ISSUE THREAD

**Issue by icarito** [kovidgoyal/rapydscript-ng#61]
Hi Kovid,
I've continued development of [Jappy Activity](http://people.sugarlabs.org/~icarito/artisan/Jappy.activity/) - lately supporting multiple tabs.

I would like to make it so that I can `import module` and it will consider the files I have open in my editor tabs. 

Is there a way I can attach code for import_path at [compilation time](https://github.com/somosazucar/artisan/blob/master/Jappy.activity/code_editor.tag.html#L108)?

Thanks!

**Comment by kovidgoyal** [comment]
Not sure what you are asking? Presumably once you click save int he editor, a subsequent import will pick up the changes. If you mean you want to dynamically change the import path you can do that via the --import-path option to the compiler or use the RAPYDSCRIPT_IMPORT_PATH environment variable.

**Comment by icarito** [comment]
Hi Kovid,

Sorry I wasn't clear enough. The editor doesn't save into the
filesystem. Neither does the compiler run on the filesystem, but in the
browser.

So what I'm asking is if there's a clean way to add imports when
compiling in the browser. The idea is that the whole process happens at
the browser level, no touching files (which could be remote, for instance).

So --import-path and RAPYDSCRIPT_IMPORT_PATH don't work for me because
I'm compiling in the browser. I have a a dictionary called files:

files = {"myimport.pyj": "def test(): pass",

             "myprogram.pyj": "from myimport import test" }

What I'm doing is, that I compile each file when pushing "Run"
(depending on which one is active). But of course, cross-file imports
such as illustrated above, won't work.

That's the question, clarified, thank you!
Sebastian

**Comment by icarito** [comment]
By the way, when I bundle it upstream, Jappy shall become part of
Sugarizer;

Sugarizer offers persistence in the form of a Journal.

You can create your (local) Sugarizer user and Journal by first going to:

http://people.sugarlabs.org/~icarito/azucarizador/ and then clicking Jappy.

Your session will be saved.

**Comment by kovidgoyal** [comment]
Ah, well it's a while since I looked at that part of the code, but basically, the compiler has a completely virtual filesystem interface. You just need to provide it with a readfile() and writefile() function to enable importing. That is how importing the standard library (for e.g. import re) works in the browser compiler. If you look at the commit where I added that functionality it might give you some clues as to how to make it more general.

**Comment by icarito** [comment]
Thanks Kovid, I came up with a solution!
Basically, I've injected into `RapydScript.file_data` some files, but I had to prepend `'__stdlib__/'`.
Here's the commit, and it's working.
https://github.com/somosazucar/artisan/commit/5c5325e607ff3957e64bbfc0121c31e577407209
