### ISSUE TITLE
Concatenating range

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#62]
Here is a report from a GlowScript user. I realize that it may not be possible to make this work in RS-NG, but I felt I should pass this on. I'm not sure, but conceivably I could deal with this myself in the context of the operator overloading machinery already in place in GlowScript.

Usually, in Python, two lists can be concatenated using the "+" operator or the extend() method.
The "+" operator works for standard lists in Glowscript VPython, but does not work for lists created using the range() method.

The following code fails:
for j in range(0,i) + range(i+1,N):
# Some code that uses (i,j) pairs
with the following error:
TypeError: range(...).+ is not a function

**Comment by kovidgoyal** [comment]
The + operator does not work for any kinds of lists. In general rs-ng does not support operator overloading at all, see the gotchas section of the readme. 

While it is certainly possible to add operator overloading, it would kill most of the performance advantage of rs-ng over python, so it would have to be made optional, which makes it not really worth it to me. IMO it is better to be consistent, other wise it is too easy to find yourself acidentally using operator overloading and introducing bugs.

**Comment by BruceSherwood** [comment]
Sorry -- I wasn't thinking clearly. Operator overloading (which is essential in GlowScript to make vector operations simple and straight-forward) is my responsibility, not yours.

**Comment by BruceSherwood** [comment]
There's an amusing side to this. I forgot that while in Python 2 you could add ranges (they being lists), in Python 3 adding ranges gives an error, so the error the user encountered is entirely appropriate. So RS-NG and GlowScript are up to date. One aspect of the operator overloading implemented in GlowScript is that you can add lists.
