### ISSUE TITLE
Please suggest solution for older WebKit `Object.defineProperties`

### ISSUE THREAD

**Issue by icarito** [kovidgoyal/rapydscript-ng#64]
Hi Kovid!
I have been loving to work with RapydScript-NG, even delving a little into the internals as required by my project. [Jappy](http://people.sugarlabs.org/~icarito/artisan/Jappy.activity/) is looking nice! I've added .zip export, more examples, and done further testing.

However, as you perhaps know, I'm trying to target certain platforms as a webview app. In particular, I've had difficulty with both Android Webviews (older Webkit) and Sugar activities (WebKit2).

They tend to fail when redefining properties with `Object.defineProperties` when they've already been defined once.

The following code fails for both of these platforms:
```
for i in range(10):
    def a(u):
        print ('lala')
    print (i)
    b = document.createElement('button')
    b.onclick = a
    document.body.appendChild(b)
```

While the android webview is hard to debug, I have a `main.py` in the [Jappy repo](https://github.com/somosazucar/artisan) that will create a standalone WebView where the issue is present.
Could you suggest a fix? I would really like to support these users and with this lots of syntax gets broken in these browsers. (For instance, I can't use ElementMaker).

Thank you for your help!

**Comment by kovidgoyal** [comment]
Hmm not sure what I can do about that. Basically RS uses Object.defineProperty to create annotations on function objects that are needed to make things like *args and keyword arguments work. 

As far as I know all modern JS engines support defining properties multiple times the same way. There are two ways I can see for you to prceed:

1) Simply move the function definition out of the loop
2) Change your copy of RS to do direct property assignment instead of using Object.defineProperties. That of course means the properties will not be read-only etc, but that should not break anything if you are careful.

**Comment by kovidgoyal** [comment]
This commit might help with elementmaker: https://github.com/kovidgoyal/rapydscript-ng/commit/931f89b058b5dde053a9ce5ee81add7dce4b82bd

**Comment by icarito** [comment]
Thanks! I will take a look at ElementMaker and if it works I may convert my examples [back] to it. 
While I may be happy to work around syntax that makes WebKit2 unhappy, I can't bring myself to teach workarounds by default, so I will be looking at patching my copy.

For the simple example given, one could move the function definition outside the loop, but sometimes, one really wants different functions for each element (using the loop iterator to change behaviour each time, for instance).

**Comment by kovidgoyal** [comment]
Should be fixed now.

**Comment by kovidgoyal** [comment]
Incidentally, I recommend against putting function definitions in loops. Instead use bind().

**Comment by icarito** [comment]
Kovid! You are awesome! I confirm that this works now.
:grinning: 
Thanks a lot!

**Comment by icarito** [comment]
Oh and thanks for the tip on `bind()`! I feel I'm _finally_ learning Javascript thanks to RapydScript!

**Comment by kovidgoyal** [comment]
You're welcome :) Finally learning javascript was one of my motivations for working on RapydScript.
