### ISSUE TITLE
Class variable

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#66]
A GlowScript user points out a problem with class variables. Is there some decorator I'm unaware of?

class C:
  C.idx = -1 # cannot omit "C."in RS, but not legal in CPython
  def __init__(self,S):
    C.idx += 1
    print(C.idx, S)
    
C('a')
C('b')

**Comment by kovidgoyal** [comment]
You want
```
class C:
  idx = -1 
  def __init__(self,S):
    C.prototype.idx += 1
    print(C.prototype.idx, S)

C()
print(C.idx)
```

This is basically a limitation of the compiler. It does not recognize class references inside class methods, so you have to add ```.prototype.``` explicitly. Outside the class you can do

```
C.idx
```

and the compiler translates it to

```
C.prototype.idx
```

for you. 

Probably something I should look into fixing, but given that referring to class variables using class names rather than self is not a common idiom...

**Comment by BruceSherwood** [comment]
I don't understand your comment about "using class names rather than self is not a common idiom". Is there something about class variables in standard Python that I'm unaware of? I thought the only way to do this in standard Python is as follows, whereas self.idx would refer to a specific instance of the class:

```
class C:
  idx = -1 
  def __init__(self,S):
    C.idx += 1
    print(self.idx, S)

C('hello')
print(C.idx)
```

**Comment by kovidgoyal** [comment]
That is correct, it is just rare to modify class variables inside instance methods, at least in my experience.

**Comment by BruceSherwood** [comment]
The user's situation seems to me a pretty common one, actually. He needed to assign a unique id number to each instance of the class, which requires using a class variable that is incremented by initialization of an instance of that class. The only alternative I can think of is to use a global variable, which is obviously less desirable. The prototype scheme you explained won't meet the user's needs because he wants the same VPython program to run both in the GlowScript environment and in a standard Python environment. This isn't a major problem, especially since there is the global variable workaround, but I hope you'll continue to consider eventually implementing this. As always, thanks much for the very rapid feedback!

**Comment by kovidgoyal** [comment]
All objects in rapydscript already have a unique id number, which just as in python, can be accessed using the id() function. 

And this issue is already fixed.

**Comment by BruceSherwood** [comment]
You're amazing, Kovid! I'll pick up the new compiler. Although there are other uses for class variables than an id number, thanks much for telling me about the id() function, which I didn't know about. Your id() function makes more sense to me, going 1, 2, 3...., than the CPython version, which as you probably know returns nonconsecutive long integers.

**Comment by kovidgoyal** [comment]
In python the id() function is usually implemented as the memory address of the object. Which means that it is only unique for an object as long as the object remains in memory. In rs-ng the id() function uses a object counter so its results are unique always (well until the counter overflows).

**Comment by BruceSherwood** [comment]
Thanks for the explanation. Your scheme seems a lot more useful.
