### ISSUE TITLE
Failure in self-test after nodejs/npm update

### ISSUE THREAD

**Issue by eli-schwartz** [kovidgoyal/rapydscript-ng#67]
When building the Arch Linux AUR package [rapydscript-ng-git](https://aur.archlinux.org/packages/rapydscript-ng-git), the check() which runs bin/rapydscript test fails with the following error:

```
Failed running: /tmp/str.pyj-es5.js
str.pyj:
assert.js:60
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: '30,000' == '30000'
    at test (/tmp/str.pyj-es5.js:3985:13)
    at /tmp/str.pyj-es5.js:4043:9
    at /tmp/str.pyj-es5.js:4184:7
    at /tmp/str.pyj-es5.js:4185:3
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at ContextifyScript.Script.runInNewContext (vm.js:59:15)
    at Object.runInNewContext (vm.js:112:38)
    at /home/eschwartz/git/pkgbuilds/rapydscript-ng-git/src/rapydscript-ng/tools/test.js:78:20
    at Array.forEach (native)
    at module.exports (/home/eschwartz/git/pkgbuilds/rapydscript-ng-git/src/rapydscript-ng/tools/test.js:45:11)


str.pyj:	test failed

There were 1 test failure(s):
str.pyj
```

Both the latest master, and checking out a previous commit that passed fine on the 10th, now fail, so I suspect the issue is somewhere in nodejs/npm which have been updated since then.

Versions:
npm 5.3.0-1
nodejs 8.1.4-1

**Comment by kovidgoyal** [comment]
Works on my arch system with node version 8.1.4 and on Travis as well, with that node version: https://travis-ci.org/kovidgoyal/rapydscript-ng/jobs/253478567

That error looks like an old version of rapydscript being used. Support for the comma format specifier was added about a month ago in 9a91d66

**Comment by eli-schwartz** [comment]
Nope, I definitely get this when running `npm install --no-optional && bin/rapydscript self --complete && bin/rapydscript test` from a fresh clone as a new user.
I have figured out, however, that the problem doesn't manifest when I build inside a clean chroot. So this would appear to be something wrong with my setup, somehow? Though I have no idea what.

**Comment by kovidgoyal** [comment]
I tried running:

```
git clone git://github.com/kovidgoyal/rapydscript-ng.git && cd rapydscript-ng && npm install --no-optional && bin/rapydscript self --complete && bin/rapydscript test
```

no errors.
