### ISSUE TITLE
`else:` statement for try-except

### ISSUE THREAD

**Issue by LordRatte** [kovidgoyal/rapydscript-ng#68]
I noticed that try-except-else doesn't work so I searched in the readme and found that you haven't had time to implement it yet - which I completely understand. Do you possibly have a timeline on when you will include it? Thanks in advance!

**Comment by kovidgoyal** [comment]
It's not particularly important to me (I tend to very rarely use it in python code I write), so no I dont have a particular timeline for it. It is somewhat messy to implement as JS has no equivalent for it, so the only way to implement it would be to use a hidden local variable.

**Comment by LordRatte** [comment]
Oh, I see. Well if you ever change your mind, I would greatly appreciate it.

**Comment by LordRatte** [comment]
Nevermind, I was replying via my email and saw you'd already made the change now. Thank you so much!
