### ISSUE TITLE
Run-time library

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#69]
Kovid, I wanted to build a run-time package for the newest compiler and I used the following procedure that worked in the past on Windows:

1) Make sure node is installed.
2) In a new folder, execute "npm install rapydscript-ng".
3) Create a file named "input.py" in this folder that contains "a=1".
4) Execute "rapydscript --bare input.py > runtime.js".

Step 2 did create a large folder named node-modules, but when I attempt step 4 I'm told rapydscript is not recognized.

**Comment by BruceSherwood** [comment]
Also, I tried the following program that should only need the new compiler 0.7.17, not the separate run-time package used with exported GlowScript programs:

class f():
    n = 0
    def __init__(self):
        self.n = n
        n += 10

a = f()
b = f()
c = f()
print(a.n, b.n, c.n)

What this prints  is unknown, unknown, unknown.

**Comment by kovidgoyal** [comment]
If you dont have rapydscript on your path, then you can always execute it as 

node.exe bin/rapydscript


And that program is not going to work, because n is not in scope in the method. If you want to refer to the class variable you need to use f.n
