### ISSUE TITLE
Illegal charcater

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#70]
Hy Kovid,

Strangely here is what I get in the compiled what loaded
in the browser (firefox)

(function(){
    "use strict";
    var ÏÏƒ_iterator_symbol = (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") ? Symbol.iterator : "iterator-Symbol-5d0927e5554349048cf0e3762a228256";
    var ÏÏƒ_kwargs_symbol = (typeof Symbol === "function") ? Symbol("kwargs-object") : "kwargs-object-Symbol-5d0927e5554349048cf0e3762a228256";
    var ÏÏƒ_cond_temp, ÏÏƒ_expr_temp, ÏÏƒ_last_exception;
    var ÏÏƒ_object_counter = 0;
var ÏÏƒ_len;

Do you have an idea ?

Regards

**Comment by kovidgoyal** [comment]
Make sure the page is using the utf-8 character set and that the server from where you are serving the javascript is setting the content-type header with character encoding utf-8.

**Comment by artyprog** [comment]
I should have found it :-)
Thank you very much Kovid
