### ISSUE TITLE
Operator Overloading

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#71]
Hy Kovid,

I know opeartor overloading would cause a great loss of performance.
But can you look at this library whiche enables overloading in local context.
I have tried to use it without success...

[https://github.com/kushal-likhi/operator-overloading-js](https://github.com/kushal-likhi/operator-overloading-js)

Regards

**Comment by artyprog** [comment]
FYI here is what I tried:

`python`
((def t():
    class V:
        def __init__(self):
            self.x = 100        

    def test():
        v = V()
        alert("v1.q")

    test()
).enableOverloading())()
```
and here is the error;

ReferenceError: \u03C1\u03C3_object_counter is not defined

**Comment by kovidgoyal** [comment]
I'm afraid I dont have the time to look at that library. But you should look into glowscript by @BruceSherwood, I believe it uses rs-ng and also adds operator overloading to it

**Comment by artyprog** [comment]
Thanks Kovid

**Comment by BruceSherwood** [comment]
You can write to me at bruce.sherwood@gmail.com. Very briefly, the library I use parses the JavaScript (that is output by RS-NG) and converts a+b to a["+"](b) which at run time invokes one of the following functions, depending on the type of a:

Number.prototype['+'] = function (r) { return this + r }
vec.prototype['+'] = vec.prototype.add

This of course affects even such forms as 3+5, but oddly enough the speed hit is not very large. This operator overloading is crucial to simplifying programs at glowscript.org that use vectors extensively to do 3D manipulations.

I agree with Kovid that trying to do operator overloading in a general way in RS-NG would not be a good idea.

**Comment by wolfv** [comment]
Modern javascript runtimes should perform function inlining and the perfomance of using a function like @BruceSherwood should be roughly equal for native types.

A dumb benchmark here: https://jsperf.com/asdasdsadassadasdadasdsadasdasdsad

Both in recent Firefox and Chrome performance is the same.
So maybe it could also be an option to actually include operator overloading in rapydscript :)

**Comment by kovidgoyal** [comment]
In the ideal case, when the calling function is JITed. And operator overloading is not just a function call, it is also a attribute lookup. One has to check if the LHS object has its own ``__add__ `` implementation. Which in JS means going up the prototype chain.

**Comment by wolfv** [comment]
you're right, it's a lot slower. I just added a test to the jsPerf from above.

**Comment by BruceSherwood** [comment]
Sorry for a typo in my summary of operator overloading. I should of course have said that a+b is converted to a["+"](b).

**Comment by BruceSherwood** [comment]
Darn! I see that I need to put that in a code envelope. I try again:

`a+b is converted to a["+"](b)`
