### ISSUE TITLE
Behaves oddly with requirejs

### ISSUE THREAD

**Issue by icarito** [kovidgoyal/rapydscript-ng#72]
Hi Kovid!
Glad to share that I'm still hacking into Jappy a lot. It's still not my default editor, but now it has real time collaboration like etherpad!

I've been trying to load RapydScript with requirejs and I'm seeing strange behaviour!

When i do `require` to `rapydscript.js` (the one created with `web_repl_export`), I get [strange result](https://gist.github.com/icarito/595f94e80a9eec055f4bc7d6b5da2a6a), what looks like a crypto lib.

I figured what I thought was a [workaround](https://github.com/somosazucar/Jappy/commit/b0e3cf9f36311517a81a6e1d9e9d91ce3bab6740#diff-1689be79274fa9eea28a6e2e834551dfR729), looking well, but then upon trying to run some code, I got `TypeError: jsSHA.jsSHA is not a constructor`.

I have put up an example for you to try it out and check out the live collaboration :-)
Thanks again for all your hard work!

**Comment by icarito** [comment]
Example at http://educa.juegos/#example_for_kovid
:-D

**Comment by kovidgoyal** [comment]
Sorry, I have no idea how require.js works. (the insanity of JS module systems was one of my big motivations to develop the rapydscript import system in the first place). Why are you using it anyway? Just put your rapydscript file into a script tag. That is how it works in the rapydscript repl, see the main.js and index.html files in the REPL.

**Comment by icarito** [comment]
I know, js modules are crazy, just getting to know them!
I'm lazy-loading rapydscript.js because that way the editor can launch much faster without having the compiler ready, it was a bottleneck.

**Comment by kovidgoyal** [comment]
Use async and/or defer on the script tag, then it wont block the rest of the page from loading.

**Comment by icarito** [comment]
Thanks for your advice! I didn't even know about `async` script tags. However now it's causing some sort of conflict with requirejs because I get:
```
Uncaught Error: Mismatched anonymous define() module: function (){return t}
http://requirejs.org/docs/errors.html#mismatch
```
As per https://stackoverflow.com/a/23467090 it would seem jsSHA is embedded in a way which confuses requirejs. If I figure it out I will share a patch. I'm already committed to requirejs from using the Sugar Web stack, not that I particularly like it, I see it has some advantages.
