### ISSUE TITLE
Missing indents

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#74]
```
n = 6
while n>0:
console.log(n)
n=n-2
    
console.log('end of program')
```

A student tripped over this; the lack of indentation is apparently not detected, and all of the following statements are inside the loop. The output is

```
6
end of program
4
end of program
2
end of program
```

**Comment by BruceSherwood** [comment]
You are really remarkable, Kovid. When I submitted the issue yesterday I joked with a colleague that you would probably fix the bug in about 10 milliseconds. You've explained to me how to build an update to the in-browser compiler, but is this something you're likely to do soon, in which case I won't bother? Or is it already updated?

**Comment by kovidgoyal** [comment]
The rs-ng REPL already has this fix.

**Comment by BruceSherwood** [comment]
I think I don't understand. When I look at https://kovidgoyal.github.io/rapydscript/repl/rapydscript.js, which is what I assume is meant by "the rs-ng REPL", I see a version number of 0.7.17, which is an old version number.

**Comment by kovidgoyal** [comment]
The version number does not change until a new release is made. BUt the
changes are there.
