### ISSUE TITLE
Experiment: Is it possible to alter language keywords (i.e.) for localization?

### ISSUE THREAD

**Issue by icarito** [kovidgoyal/rapydscript-ng#75]
Please advice if this is possible with RapydScript-NG:
[Python Keywords in Local Language](https://github.com/aroberge/experimental/blob/master/experimental/transformers/french_syntax.py)

Of course the exact same approach won't work, but are there hooks I could use or implement for doing this?
Thanks in advance for your advice!

**Comment by icarito** [comment]
From the linked page:
```
Code like:
    si Vrai:
        imprime("French can be used.")
    autrement:
        print(Faux)
Will be translated to
    if True:
        print("French can be used.")
    else:
        print(False)
```

**Comment by kovidgoyal** [comment]
No, not really. You would essentially have to fork the compiler and replace/supplement the keyword definitions.
