### ISSUE TITLE
import folder.module1,folder.module2 as module1,module2 throws Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by rafi16jan** [kovidgoyal/rapydscript-ng#83]
Based on here https://github.com/kovidgoyal/rapydscript-ng/issues/22, since you doesn't allow "from folder import module1, module2" instead you suggest import folder.module1 as module1. How to import multiple modules from a folder and rename it as their names. I tried "import folder.module1 as module1, folder.module2 as module2" and it's a syntax error. Then I tried "import folder.module1, folder.module2 as module1, module2" and it throws TypeError: Cannot read property 'prototype' of undefined

How do I get a workaround?

**Comment by rafi16jan** [comment]
This is the full traceback:

test.pyj:2072
    child.prototype = Object.create(parent.prototype);
                                          ^

TypeError: Cannot read property 'prototype' of undefined
    at ρσ_extends (test.pyj:2072:43)
    at test.pyj:4339:9
    at test.pyj:4359:7
    at test.pyj:4360:3
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.runInNewContext (vm.js:93:38)
    at write_output (/data/data/com.termux/files/home/projects/pouchdb-orm/node_modules/rapydscript-ng/tools/compile.js:85:16)
    at compile_single_file (/data/data/com.termux/files/home/projects/pouchdb-orm/node_modules/rapydscript-ng/tools/compile.js:133:9)
    at tryToString (fs.js:457:3)

**Comment by kovidgoyal** [comment]
Huh? ```from x import a, b``` is perfectly well allowed, although rather than importing full modules, you should instead import symbols from modules, it is a better pattern.

Your traceback appears to have something to do with inheritance in a class. Hard to day without access to the source.

**Comment by rafi16jan** [comment]
Wait dont close this issue, my source is published on github https://github.com/rafi16jan/pouchdb-orm. See at test.pyj if I use from orm import models, fields it will throws "The symbol "models" is not exported from the module".

**Comment by rafi16jan** [comment]
Oh I get it now, yeah there are no symbols in orm/__init__.pyj but in that file I import the two modules, models.pyj and fields.pyj so the symbols should be exported.

**Comment by rafi16jan** [comment]
@kovidgoyal sorry I mention you, but im confused why its not exported even though I import it (just like a normal python libraries)

**Comment by kovidgoyal** [comment]
rs-ng does not automatically re-export imported symbols (IIRC this is a performance optimization). Assign them to module level variables and they should be exported, or better yet, just import from the submodules directly. There are several differences between python and rs-ng import systems. The biggest being that importing is compile time in rs-ng and runtime in python. Being compile time leads to many other smaller differences.

**Comment by rafi16jan** [comment]
You mean, 

import module
module = module

?

**Comment by kovidgoyal** [comment]
import module

a = module.a
b = module.b

then you will be able to import a and b from this module.

**Comment by rafi16jan** [comment]
No if I do that eg:

import models
Model = models.Model

then in the test.pyj I cant import orm.models, but orm.Model. I want to get models.Model.

Ok its actually ok if I cant get "from folder import module1, module2" but can I get the "import folder.module1 as module1, folder.module2 as module2" ? It's weird that it throws https://github.com/kovidgoyal/rapydscript-ng/issues/83#issuecomment-331127218

**Comment by rafi16jan** [comment]
or can you make "import folder.module1, folder.module2" import module1 and module2 symbol?

**Comment by rafi16jan** [comment]
Because it will take a long line just to import the symbols, I dont want to write

import orm.fields.Char as Char
import orm.fields.Float as Float
import orm.fields.Integer as Integer

That will be painful, oh yeah I got mind blown because i cant even "import folder.module" and then call it by folder.module nor can I "import folder" and then access modules that exist at the said folder. So the problem isn't just at renaming it but at the whole 'symbol or module' problem.

**Comment by rafi16jan** [comment]
OOOH and I got another mind-blown. The syntax "import orm.models, orm.fields as models, fields" if I print(models) it will show the json and the classess and function that exist at orm.models. But, if I print(fields) it will print an empty json.

**Comment by rafi16jan** [comment]
If this can't be fixed or you doesn't think this is a bug, then I will stick to:

import orm.models as models
import orm.fields as fields

the shortest syntax that works.

**Comment by kovidgoyal** [comment]
I just you wear a helmet, it will help prevent your ind from blowing up so much. ANd write

from orm.fields import Char, Float, Integer

And take a moment to calculate how much less you have to type when you do that, since you dont need to type the unneccessary models prefix every time you refer to something from models.
