### ISSUE TITLE
Task Runner

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#84]
Hy Kovid,

How can I use Rapydscript in a task runner like gulp ?
The existing plugin 'gulp-rapyd' does not work with your  rapydscript-ng

Regards

**Comment by kovidgoyal** [comment]
Sorry I dont know anything about gulp and I dont maintain gulp-rapyd.

**Comment by kovidgoyal** [comment]
Most likely you just have to change gulp-rapyd to use the command line arguments rs-ng expects instead of those the original RS expects.

**Comment by artyprog** [comment]
Thanks Kovid,

In fact here is the problem.
I would like to do in a node js file:

var rapyd = require('rapydscript-ng')

and use rapyd to compile  pyj files

**Comment by artyprog** [comment]
Otherwise,

When you develop do you use a tool to compile 'pyj' on save ?

**Comment by kovidgoyal** [comment]
Just call the rapydscript compiler to compile files. It's a normal command line program.

**Comment by artyprog** [comment]
I was a little lazy :-)

**Comment by kovidgoyal** [comment]
In fact, because the rs-ng compiler does incremental compilation it is fast enough that you can call it automatically everytime you save in your editor. I have my editor setup to use the rs-ng linter and compiler automatically on every save.
