### ISSUE TITLE
Problem importing value

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#85]
Hy Kovid

In  **m1.pyj** I have :
```
G = 1
def getG():
    return G
```

In **m.pyj** I have

```
import m1
m1.G = 1000
print(m1.getG())
```

I expexted 1000 to be printed, but it is still 1

Regards
`

**Comment by kovidgoyal** [comment]
You cannot change module values in rs-ng. You want to do that, create a setter function in m1.pyj and call it from m2.pyj

**Comment by artyprog** [comment]
Thank you Kovid.
