### ISSUE TITLE
Compiling script

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#86]
Hy Kovid,

I am  compiling a script on my linux box.
and I am sending the result via websocket on mybrowser

Is there a way to 'clean' this files because it can't ve evaluated by Javascript.
Mainy illegal characters

Regards

**Comment by kovidgoyal** [comment]
There are no illegal characters. Make sure to encode and decode using the UTF-8 encoding.

**Comment by artyprog** [comment]
Thanks Kovid,
I suspected this...
