### ISSUE TITLE
Compliance

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#87]
Kovid, I timed a rather typical but computationally intense GlowScript VPython program tinyurl.com/HardSphereGas and found that it runs many times faster than using installed Python, even if one goes to the trouble of using numpy or numba or cython. This could make the scheme attractive to computational scientists, except that the large world of Python modules isn't easily accessible. Modules written in pure Python could be converted by RapydScript-NG, and modules written in C/C++ might be fairly easily converted, given the similarity to JavaScript. This would  be a big task and would require a concerted effort by a large number of volunteers, but this wouldn't be an absolutely impossible large project. File I/O is problematic in a browser, but maybe one could run in a nodejs environment. A specific question for you is this: In your expert opinion, what are the most important differences today of RS-NG from standard Python? I realize that I'm talking of a kind of fantasy, but one that seems at least worth thinking about.

I'll also mention that I recently did some timing of the operator overloading I'm doing, and the overhead is relatively small. Surprisingly, I think it might be feasible to handle operator overloading in RS-NG.

Should you wish to do so, you could write to me at bruce.sherwood@gmail.com.

**Comment by kovidgoyal** [comment]
While python modules are not accessible, the even larger world of javascript modules is accessible. Although, to be fair, I dont know if there are a lots of JS libraries for numerical computation.

As for major differences with python there is a section in the readme file on it. https://github.com/kovidgoyal/rapydscript-ng#gotchas

You dont actually need to convert modules written in C/C++. Better to compile them to WebAssemby using emscripten and access that directly from rs-ng code. 

rs-ng runs fine in node. 

Operator overloading as you implement it is not general enough to actually match python semantics. Implementing general enough operator overloading is expensive. If you want to focus on performance, operrator overloading is not a good idea.

**Comment by BruceSherwood** [comment]
Thanks for the helpful reply. My impression is that JS libraries for numerical computation are not well developed. I even saw a basic one that was pretty defective. Knowing almost nothing about the tools, I didn't realize that WebAssembly and emscripten could be used for converting C/C++ modules.
