### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#89]
In the README "Gotchas" is the following: "Similarly, [1] + [1] is a new list in Python, but a string in JavaScript." When I try this I get a new list [1,1], and I don't think I'm doing anything in my pre- and post-processing to get this result.

The next sentence says that method calls in JavaScript are very slow compared to raw operators, but I've been surprised to find that the overhead is surprisingly small, something like 30%. What do your measurements show? I have to take your word for it that handling overloading in general might be difficult or impossible, and that the GlowScript approach isn't generalizable. But execution speed doesn't seem to be a killer issue, and there could be a flag saying whether it is to be used.

**Comment by kovidgoyal** [comment]
No, [1] + [1] is '[1][1]' in rapydscript, try it in the repl. And as I I've said, before, operator overloading has too high an overhead for me to be interested in implementing it.

**Comment by BruceSherwood** [comment]
Yeah, my mistake about [1]+[1]. I had forgotten that buried in my code I do handle that case. Sorry.
