### ISSUE TITLE
Not an issue a suggestion...

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#9]
Kovid,

Would it be possible, for the compiler to accept a string as an input ?
Indeed I would like to create a webservice so that i send the  user code via ajax or websocket and pass the string directly to the compiler and get the output on stdout ?

**Comment by kovidgoyal** [comment]
It already does. 

echo 'print(1)' | rapydscript

**Comment by artyprog** [comment]
Thank you Kovid
