### ISSUE TITLE
Missing error message?

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#90]
A student had the statement r= in a program, which did not throw an error. Shouldn't it? It's true that the program ran okay, but still....

The larger issue is that for our educational purposes it would be useful to be able to tell RapydScript to be strict in compilation, so that for example calling a function before it is defined would be an error, and !x instead of not x would be an error. The main reason for wanting this strictness is that students may start with GlowScript VPython and in later, more advanced courses, graduate to using CPython, and it would be good where not overly expensive to catch what would be errors in CPython. Some of these errors (probably including these two) I can catch myself in the preprocessing I do, but you can do a better job than I can.

**Comment by kovidgoyal** [comment]
r= given me an error.
```
echo 'a=1;r=;print(x)' | rapydscript    
<stdin>:Unexpected token: punc «;» (line: 1, col: 6, pos: 6)
```

In general trying to match the cpython interpreter's every error behavior is both too much work and not a goal, as there are many things that rs supports that cpython does not. That said patches to catch specific errors, where possible, are welcome.

**Comment by BruceSherwood** [comment]
Thanks much for the test. I now see why it wasn't caught in the GlowScript environment but is caught by RadydScript itself.
