### ISSUE TITLE
"list.append is not a function". 

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#91]
This runs in python as I want.    (It's a fixed-length stack) 

But  at https://kovidgoyal.github.io/rapydscript/repl/ and at glowscript,  
I get  "list.append is not a function".  

what to do in a case like this?

class threeList(list):
    def append(self, item):
        list.append(self, item)
        while len(self)>3:
            self.pop(0)

d=threeList()
for i in range(6):
    d.append(i)
    print(d)

##### correct output in python
[0]
[0, 1]
[0, 1, 2]
[1, 2, 3]
[2, 3, 4]
[3, 4, 5]

**Comment by kovidgoyal** [comment]
There is no list class in rapydscript (list is implemented based on the JS Array object). 
```py
def mylist():
    ans = []
    ans.append = def(val):
        while this.length > 2:
            this.shift()
        this.push(val)
    return ans

l = mylist()
l.append(1), l.append(2), l.append(3), l.append(4)
print(l)
```

**Comment by BruceSherwood** [comment]
But is there a general question concerning whether or when one can inherit from a built-in class. I did try inheriting from Array without success. Your particular solution isn't one that will run both in CPython and in RapydScript, which is what the user is interested in achieving (and there are of course ways to write this particular class that will work in both environments, at least with respect to this particular append method). More and more people are using RapydScript-NG through GlowScript VPython and using their same code in the CPython version of VPython (which has the same API for 3D animations), so there is growing interest in knowing the details of what is likely to work in both cases. Happily, I can report that most of the incompatibilities are pretty esoteric edge cases, such as the present case. You've succeeded so well that when there is an incompatibility it comes as a surprise. Note too that probably 99% of the GlowScript VPython users know nothing about JavaScript, whereas your audience of web programmers do know JavaScript well, which makes a difference.

**Comment by kovidgoyal** [comment]
Yeah, well this is unavoidable because of limitations of how arrays work in ES 5. Basically, you cannot subclass Array, without running into various issues. And the code works fine in python with a couple of modifications, which you can put behind a conditional, something like:

```py
def mylist():
    ans = []
    def append(self, val):
        if hasattr(list, 'prototype'):
            while this.length > 2:
                this.shift()
            this.push(self)
        else:
            while len(self) > 2:
                self.pop(0)
            list.append(this, val)
    ans.append = append
    return ans

```

**Comment by BruceSherwood** [comment]
Okay, thanks for the explanation. (Presumably you mean self.pypop(0) in the RS case?)

The README discusses class static methods but says nothing about class variables. They don't seem to work, but is there a flag that makes them work?

**Comment by kovidgoyal** [comment]
No, I used this.shift() which is the same as pypop() but faster. class variables work fine as far as I know.

**Comment by BruceSherwood** [comment]
You're right. I wrote a simpler case of using a class variable and it indeed does work, which is a good reason not to need special documentation! I've asked the guy to simplify his example to see why his fails.

**Comment by BruceSherwood** [comment]
Yup. He had a mistake in his example (which was a bit too complicated for me to spot his error).

**Comment by jonschull** [comment]
Yes, and  thanks for your attention!
