### ISSUE TITLE
Inheriting from a base class such as "list"

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#92]
A GlowScript user tried the following and gets the error "list.append is not a function". Your README discusses inheriting from one's own class, but is there something I'm missing about inheriting from a builtin class such as list (or perhaps Array)?

```
class threeList(list):
    def append(self, item):
        list.append(self, item)
        while len(self)>3:
            self.pypop(0)

d = threeList()
for i in range(6):
    d.append(i)
    print(d)
```

**Comment by kovidgoyal** [comment]
dup of #91
