### ISSUE TITLE
pypop()

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#93]
I believe that the pypop() function, list_pop(index), is missing a check for index === undefined, in which case it should return the last item in the list.  It currently returns the first item in the list, as though one had said pypop(0).

**Comment by BruceSherwood** [comment]
I should mention that in the compiler, in the minified runtime package, I was surprised to find two copies of the list_pop function.

**Comment by kovidgoyal** [comment]
IIRC the embedded compiler contains multiple copies of the baselib, compiled with different compiler flags, so that it can output the version of the baselib matching whatever compile flags are passed to it.
