### ISSUE TITLE
dict keys() and values() not right in REPL (but right in rapydscript from command line)

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#98]
In the online REPL at https://kovidgoyal.github.io/rapydscript/repl/

When d is defined this way, 
   d=dict(a=1,b=2) 
the online REPL returns {} for both d.keys() and d.values() 
(wrong.  Also wrong in glowscript)

list(d.keys()) and list(d.values())  return correct  answers

![pasted_image_2_15_18__3_05_pm](https://user-images.githubusercontent.com/53673/36278360-9d74bcc4-1261-11e8-8efd-1c333dd341c3.jpg)

When d is declared this way: d={'a':1, 'b':2}
d.keys() and d.values() are rejected with "not a function"

![pasted_image_2_15_18__3_12_pm](https://user-images.githubusercontent.com/53673/36278737-b23082d2-1262-11e8-8d9d-f25ffa355b78.jpg)

The rapydscript compiler gets it all right.
![pasted_image_2_15_18__3_06_pm](https://user-images.githubusercontent.com/53673/36278405-c628bb48-1261-11e8-8a62-c4529892ce78.jpg)

( Perhaps its helpful to note that In python3, keys() and values() are iterators.  in python2 they were lists. )

Thanks for all you do!

**Comment by kovidgoyal** [comment]
Again, I cannot reproduce 

![screenshot_20180216_081520](https://user-images.githubusercontent.com/1308621/36291543-89f25b08-12f1-11e8-86f4-06530c935cc2.png)

d is defined using dict() and e with {} keys() exists for d and not for e, as noted in the readme in the section on dicts.

**Comment by jonschull** [comment]
I think you _did_ reproduce.  And you explained.  Thanks.

FYI the string representation of d.keys() in the online REPL is pretty misleading: **{}**
In the commandline REPL, it is clear:  **MapIterator { 1, 2 }**

But I learn something each time.  
This time, I learned to go over the readme more carefully before reporting an issue ;-)

FYI2.  Glowscript can import  "from __python__ ..."
