### ISSUE TITLE
representation of Generator expresssion  (x for x in l)

### ISSUE THREAD

**Issue by jonschull** [kovidgoyal/rapydscript-ng#99]
In the online repl, The representation of the generator expression (x for x in l) is "{}"

![pasted_image_2_18_18__11_19_am](https://user-images.githubusercontent.com/53673/36354132-a057727c-149d-11e8-96d6-253da303a9c7.jpg)
 
(for l = [1,2,3],  list(x for x in l) renders correctly as [1,2,3])

Regards,

**Comment by kovidgoyal** [comment]
Yes, that's what generic objects are represented as in JS. In python if you try creating a generator, you get something like
<generator object <genexpr> at 0x7fd68fecff68>

which is marginally more useful, but not enough that I care to implement it in RS. If you feel differently, patches are welcome.

**Comment by jonschull** [comment]
got it

**Comment by jonschull** [comment]
I don't think I'd be able to contribute patches; I'm no javascript programmer, as you can easily see.
